"""pjm-h15 — score G1 / G2 / G3 / G4 from the committed control and the arm.

ZERO LP. Every operand is read from a ``legitimacy_diagnostics.json``: the
CONTROL's (the pjm-h14 keeper pair, with the touchpoint's regenerated by this
lane because that bundle ships none) and the ARM composite's.

The gates are PRECOMMIT-pjm-h15-2026-09-20.md §4, quoted verbatim in the code
below and NEVER re-read once a number lands. G5 is scored separately and at
zero LP by ``pjm_h15_g5_window_only_phase0.py`` (it needs the fleet builder,
not a diagnostics file).

Usage:
    python3 scripts/probes/pjm_h15_score_gates.py \
        --control-span   results/calibration/pjm_h14_coalmustrun_span/legitimacy_diagnostics.json \
        --control-touch  results/calibration/_pjm_h15_touchpoint_d4_rederived.json \
        --arm results/calibration/pjm_h15_coalwindow_span/legitimacy_diagnostics.json \
        --arm results/calibration/pjm_h15_coalwindow_touch/legitimacy_diagnostics.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

#: PRECOMMIT §4 G2 — the coal must-run FAMILY. Every other D-2 id is "outside".
COAL_FAMILY = {"coal_mustrun"}

#: PRECOMMIT §4 G2 — the bar, in ABSOLUTE TWh (never a share: pjm-h14's G5
#: failed on a denominator move in a 1.7 TWh class).
G2_BAR_TWH = 0.05

#: PRECOMMIT §4 G3(a) — a control conduct FAIL row is in G3's population iff
#: its own-year fraction is at least this much BELOW its pooled fraction.
G3_FRAC_DROP = 0.05

#: PRECOMMIT §4 G3(b) — the control's total coal conduct FAIL floored energy.
G3B_CONTROL_TOTAL_TWH = 0.5574


def load(paths: list[Path]) -> tuple[dict, dict]:
    """Return (D2 rows keyed (year, mech, class), D4 conduct rows keyed (year, plant))."""
    d2: dict[tuple, dict] = {}
    d4: dict[tuple, dict] = {}
    for p in paths:
        doc = json.loads(p.read_text())
        diag = doc["diagnostics"]
        for r in diag.get("D2", {}).get("rows", []):
            d2[(int(r["year"]), str(r["mechanism"]), str(r.get("class", "")))] = r
        for r in diag.get("D4", {}).get("rows", []):
            if r["floor"] == "coal_mustrun" and r["check"] == "unit-conduct":
                d4[(int(r["year"]), str(r["plant"]))] = r
    return d2, d4


def fracs(by_year_csv: Path, pooled_csv: Path) -> tuple[dict, dict]:
    import pandas as pd

    pooled = pd.read_csv(pooled_csv)
    pooled = pooled[(pooled.plant_group == "COAL") & (pooled.get("status", "ok") == "ok")]
    pm = {}
    for r in pooled.itertuples(index=False):
        try:
            f = float(r.online_frac)
        except (TypeError, ValueError):
            continue
        if f == f:
            pm[str(int(r.plant_code))] = f
    by = pd.read_csv(by_year_csv)
    by = by[by.plant_group == "COAL"]
    om = {
        (int(r.year), str(int(r.plant_code))): float(r.online_frac)
        for r in by.itertuples(index=False)
        if float(r.online_frac) == float(r.online_frac)
    }
    return pm, om


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--control", nargs="+", required=True)
    ap.add_argument("--arm", nargs="+", required=True)
    ap.add_argument("--pooled", default="data/raw/_processed-legacy/thermal_tranches_PJM.csv")
    ap.add_argument("--by-year",
                    default="data/raw/_processed-legacy/thermal_tranches_online_frac_by_year_PJM.csv")
    ap.add_argument("--json-out", default=None)
    a = ap.parse_args()

    c2, c4 = load([Path(p) for p in a.control])
    a2, a4 = load([Path(p) for p in a.arm])
    pm, om = fracs(Path(a.by_year), Path(a.pooled))
    verdicts: dict[str, object] = {}

    # ---- G1: the arm fires -------------------------------------------------
    print("### G1 — the arm's D-2 coal_mustrun forced TWh differs from control in EVERY year\n")
    years = sorted({y for (y, m, _) in c2 if m == "coal_mustrun"})
    g1_rows, g1 = [], True
    for y in years:
        k = [kk for kk in c2 if kk[0] == y and kk[1] == "coal_mustrun"]
        ck = c2[k[0]]["forced_twh"] if k else None
        ka = [kk for kk in a2 if kk[0] == y and kk[1] == "coal_mustrun"]
        av = a2[ka[0]]["forced_twh"] if ka else None
        ok = ck is not None and av is not None and abs(av - ck) > 0
        g1 &= ok
        g1_rows.append(dict(year=y, control=ck, arm=av,
                            d=None if (ck is None or av is None) else round(av - ck, 4), fires=ok))
        print(f"  {y}: control {ck}  arm {av}  d {g1_rows[-1]['d']}  -> {'fires' if ok else 'INERT'}")
    verdicts["G1"] = dict(passed=bool(g1), rows=g1_rows)
    print(f"\n  G1: {'PASS' if g1 else 'FAIL'}\n")

    # ---- G2: nothing outside the coal seam ---------------------------------
    print(f"### G2 — no D-2 id outside {sorted(COAL_FAMILY)} moves forced TWh by > {G2_BAR_TWH} TWh\n")
    g2_rows, g2 = [], True
    for key in sorted(set(c2) | set(a2)):
        y, mech, cls = key
        if mech in COAL_FAMILY:
            continue
        cv = c2.get(key, {}).get("forced_twh")
        av = a2.get(key, {}).get("forced_twh")
        if cv is None or av is None:
            g2_rows.append(dict(year=y, mechanism=mech, cls=cls, control=cv, arm=av,
                                d=None, breach=True))
            g2 = False
            print(f"  {y} {mech:28} {cls:12} MISSING on one side -> BREACH")
            continue
        d = av - cv
        breach = abs(d) > G2_BAR_TWH
        g2 &= not breach
        g2_rows.append(dict(year=y, mechanism=mech, cls=cls, control=cv, arm=av,
                            d=round(d, 4), breach=breach))
        if breach:
            print(f"  {y} {mech:28} {cls:12} {cv:9.4f} -> {av:9.4f}  d {d:+.4f}  BREACH")
    verdicts["G2"] = dict(passed=bool(g2), bar_twh=G2_BAR_TWH, rows=g2_rows)
    worst = max((r for r in g2_rows if r["d"] is not None), key=lambda r: abs(r["d"]), default=None)
    if worst:
        print(f"  largest |d| outside the family: {worst['year']} {worst['mechanism']} "
              f"{worst['cls']} {worst['d']:+.4f} TWh")
    print(f"\n  G2: {'PASS' if g2 else 'FAIL'}\n")

    # ---- G3: rule 17 served on the reachable population --------------------
    print("### G3 — (a) every reachable control FAIL clears or halves; (b) total FAIL energy <= "
          f"{G3B_CONTROL_TOTAL_TWH} TWh\n")
    ctrl_fail = {k: r for k, r in c4.items() if r["verdict"] != "pass"}
    g3a_rows, g3a = [], True
    print("  control conduct FAIL rows, and whether this card can reach them:")
    for (y, plant), r in sorted(ctrl_fail.items()):
        pf, of = pm.get(plant), om.get((y, plant))
        reach = pf is not None and of is not None and of <= pf - G3_FRAC_DROP
        ar = a4.get((y, plant))
        cleared = ar is not None and ar["verdict"] == "pass"
        halved = ar is not None and float(ar["floored_twh"]) <= 0.5 * float(r["floored_twh"])
        ok = (not reach) or cleared or halved
        g3a &= ok
        g3a_rows.append(dict(year=y, plant=plant, pooled=pf, own=of, reachable=reach,
                             control_floored_twh=r["floored_twh"],
                             arm_floored_twh=None if ar is None else ar["floored_twh"],
                             arm_verdict=None if ar is None else ar["verdict"],
                             cleared=cleared, halved=halved, gate_ok=ok))
        print(f"    {y} {plant:>6}  pooled {pf}  own {of}  reachable={reach}  "
              f"floored {r['floored_twh']} -> {None if ar is None else ar['floored_twh']}  "
              f"verdict {None if ar is None else ar['verdict']}  -> {'ok' if ok else 'FAIL'}")
    arm_fail_total = round(sum(float(r["floored_twh"]) for r in a4.values()
                               if r["verdict"] != "pass"), 4)
    g3b = arm_fail_total <= G3B_CONTROL_TOTAL_TWH
    print(f"\n  (b) arm total coal conduct FAIL floored energy: {arm_fail_total} TWh "
          f"vs control {G3B_CONTROL_TOTAL_TWH} -> {'PASS' if g3b else 'FAIL'}")
    verdicts["G3"] = dict(passed=bool(g3a and g3b), a_passed=bool(g3a), b_passed=bool(g3b),
                          arm_fail_total_twh=arm_fail_total, rows=g3a_rows)
    print(f"\n  G3: {'PASS' if (g3a and g3b) else 'FAIL'}\n")

    # ---- G4: no NEW conduct failure ----------------------------------------
    print("### G4 — the arm adds ZERO coal conduct FAIL rows the control does not carry\n")
    new = sorted(k for k, r in a4.items() if r["verdict"] != "pass" and k not in ctrl_fail)
    for (y, plant) in new:
        r = a4[(y, plant)]
        cr = c4.get((y, plant))
        print(f"  NEW FAIL {y} {plant}: floored {r['floored_twh']} bind {r['binding_hours']} "
              f"med {r['measured_median_mw']} (control verdict "
              f"{None if cr is None else cr['verdict']})")
    g4 = not new
    verdicts["G4"] = dict(passed=bool(g4), new_failures=[{"year": y, "plant": p} for y, p in new])
    print(f"\n  G4: {'PASS' if g4 else 'FAIL'}\n")

    print("### SUMMARY")
    for g in ("G1", "G2", "G3", "G4"):
        print(f"  {g}: {'PASS' if verdicts[g]['passed'] else 'FAIL'}")
    print("  G5: scored by pjm_h15_g5_window_only_phase0.py (zero LP, fleet builder)")

    if a.json_out:
        Path(a.json_out).write_text(json.dumps(verdicts, indent=1))
        print(f"\nwrote {a.json_out}")


if __name__ == "__main__":
    main()
