"""Tests for ``scripts.lib.rubric_consts`` — the generated scorer-constants JS.

The Run Explorer used to hand-mirror ``calibration_verdict``'s C1 bands and
gate membership in JavaScript. Wave 5C replaced the copy with a generated
``frontend/data/backcast/rubric-consts.js``; these tests pin the two properties
that make that safe: the payload really is the scorer's own values (no second
source of truth), and the rendered bytes are deterministic (unchanged constants
re-render identically, so concurrent calibration sessions running
``build_manifest.py`` never conflict on the file).
"""

from __future__ import annotations

import json
import re

from scripts import calibration_verdict as cv
from scripts.lib import rubric_consts


def _payload(text: str) -> dict:
    m = re.search(r"window\.BC\.rubricConsts=(\{.*\});\s*$", text, re.S)
    assert m, "rubric-consts.js does not carry the expected assignment"
    return json.loads(m.group(1))


def test_values_come_from_the_scorer():
    c = rubric_consts.rubric_consts()
    assert c["fuelmixVolLoadFrac"] == cv.FUELMIX_VOL_LOAD_FRAC
    assert c["fuelmixVolCapTWh"] == cv.FUELMIX_VOL_CAP_TWH
    assert c["fuelmixSharePP"] == cv.FUELMIX_SHARE_PP
    assert c["gasClasses"] == list(cv.GAS_CLASSES)
    assert c["coalClasses"] == list(cv.COAL_CLASSES)
    assert c["fuelmixExcluded"] == sorted(cv.FUELMIX_EXCLUDED)
    assert c["nonfossilFuels"] == list(cv.NONFOSSIL_FUELS)
    assert c["rubricVersion"] == cv.RUBRIC_VERSION


def test_render_is_deterministic_and_marked_generated():
    first = rubric_consts.render_js()
    assert first == rubric_consts.render_js()
    assert first.startswith("// GENERATED by scripts/build_manifest.py")
    # The frozenset must not leak set-iteration order into the wire format.
    assert _payload(first)["fuelmixExcluded"] == sorted(cv.FUELMIX_EXCLUDED)


def test_rendered_payload_round_trips():
    assert _payload(rubric_consts.render_js()) == json.loads(
        json.dumps(rubric_consts.rubric_consts())
    )


def test_write_creates_the_frozen_filename(tmp_path):
    out = rubric_consts.write_rubric_consts_js(tmp_path)
    assert out.name == "rubric-consts.js"
    assert _payload(out.read_text())["source"] == "scripts/calibration_verdict.py"


def test_holdout_tiers_come_from_the_policy_module():
    """The rule-22 tier map is the policy module's, not a JS-side copy.

    The Run Explorer labels a held-out year's tier in its year dropdown
    (``2022 — validation holdout``) and picks the banner caveat from it. Before
    2026-08-09 there was no way to do that without typing 2019/2022/2026 into
    JavaScript — the same drift trap the C1 bands above were moved out of. The
    payload must therefore stay bound to ``scripts.lib.holdout_policy``.
    """
    from scripts.lib import holdout_policy as hp

    tiers = rubric_consts.rubric_consts()["holdoutTiers"]
    assert tiers[hp.TIER_TRAIN] == sorted(hp.CALIBRATION_YEARS)
    assert tiers[hp.TIER_VALIDATION] == sorted(hp.VALIDATION_YEARS)
    assert tiers[hp.TIER_LOCKED] == sorted(hp.LOCKED_TEST_YEARS)
    # Sorted lists, not sets: iteration order is not a wire format.
    for years in tiers.values():
        assert years == sorted(years)


def test_holdout_tiers_agree_with_tier_for_year():
    """The JS consumer reproduces ``tier_for_year`` on every enumerated year.

    The page's ``yearTier()`` tests the three lists in train -> validation ->
    locked order and falls through to ``locked_test``. That is only equivalent
    to the Python gate if the lists are disjoint, so pin it here rather than in
    a comment.
    """
    from scripts.lib import holdout_policy as hp

    tiers = rubric_consts.rubric_consts()["holdoutTiers"]
    seen: set[int] = set()
    for tier, years in tiers.items():
        assert not (seen & set(years)), f"{tier} overlaps an earlier tier"
        seen |= set(years)
        for y in years:
            assert hp.tier_for_year(y) == tier
    # Fail-closed default: an unenumerated year is locked-test on both sides.
    assert hp.tier_for_year(1999) == hp.TIER_LOCKED
    assert 1999 not in seen
