"""Tests for ``scripts.lib.rubric_consts`` — the generated scorer-constants JS.

The Run Explorer used to hand-mirror ``calibration_verdict``'s C1 bands and
gate membership in JavaScript. Wave 5C replaced the copy with a generated
``frontend/data/backcast/rubric-consts.js``; these tests pin the two properties
that make that safe: the payload really is the scorer's own values (no second
source of truth), and the rendered bytes are deterministic (unchanged constants
re-render identically, so concurrent calibration sessions running
``build_manifest.py`` never conflict on the file).
"""

from __future__ import annotations

import json
import re

from scripts import calibration_verdict as cv
from scripts.lib import rubric_consts


def _payload(text: str) -> dict:
    m = re.search(r"window\.BC\.rubricConsts=(\{.*\});\s*$", text, re.S)
    assert m, "rubric-consts.js does not carry the expected assignment"
    return json.loads(m.group(1))


def test_values_come_from_the_scorer():
    c = rubric_consts.rubric_consts()
    assert c["fuelmixVolLoadFrac"] == cv.FUELMIX_VOL_LOAD_FRAC
    assert c["fuelmixVolCapTWh"] == cv.FUELMIX_VOL_CAP_TWH
    assert c["fuelmixSharePP"] == cv.FUELMIX_SHARE_PP
    assert c["gasClasses"] == list(cv.GAS_CLASSES)
    assert c["coalClasses"] == list(cv.COAL_CLASSES)
    assert c["fuelmixExcluded"] == sorted(cv.FUELMIX_EXCLUDED)
    assert c["nonfossilFuels"] == list(cv.NONFOSSIL_FUELS)
    assert c["rubricVersion"] == cv.RUBRIC_VERSION


def test_render_is_deterministic_and_marked_generated():
    first = rubric_consts.render_js()
    assert first == rubric_consts.render_js()
    assert first.startswith("// GENERATED by scripts/build_manifest.py")
    # The frozenset must not leak set-iteration order into the wire format.
    assert _payload(first)["fuelmixExcluded"] == sorted(cv.FUELMIX_EXCLUDED)


def test_rendered_payload_round_trips():
    assert _payload(rubric_consts.render_js()) == json.loads(
        json.dumps(rubric_consts.rubric_consts())
    )


def test_write_creates_the_frozen_filename(tmp_path):
    out = rubric_consts.write_rubric_consts_js(tmp_path)
    assert out.name == "rubric-consts.js"
    assert _payload(out.read_text())["source"] == "scripts/calibration_verdict.py"
