"""Guard that ``data/dictionary/data-dictionary.md`` stays a faithful render.

The data dictionary is generated by ``scripts/render_data_dictionary.py`` from
two sources: the schema YAMLs (per-column tables) and the provenance metadata
embedded in ``data/clean`` (the ISO x year coverage matrix). These tests assert
the committed doc has not drifted from a fresh render.

The clean tree is gitignored (derived/disposable), so the full byte-for-byte
comparison is gated on it being present — regenerate it with
``python scripts/regenerate_clean.py`` to exercise the coverage matrix. The
schema-driven per-column tables, by contrast, need no data and are always
checked, so a schema edit that bypasses a re-render is caught even in CI.
"""

import unittest

from scripts import render_data_dictionary as render
from scripts.lib import clean_io


def _clean_tree_populated() -> bool:
    """Whether any curated clean Parquet exists to build the coverage matrix."""
    return any(render.paths.CLEAN_DIR.rglob("*.parquet"))


class DataDictionarySyncTest(unittest.TestCase):
    def test_doc_exists(self):
        """The committed data dictionary is present."""
        self.assertTrue(
            render.DOC_PATH.is_file(), f"missing {render.DOC_PATH}"
        )

    def test_per_column_tables_match_schemas(self):
        """Every datatype's per-column table matches a fresh schema render.

        This is hermetic — it reads the schema YAMLs, not the clean tree — so it
        catches a schema change that did not get re-rendered into the doc.
        """
        committed = render.DOC_PATH.read_text()
        for datatype in render.DATATYPE_ORDER:
            with self.subTest(datatype=datatype):
                table = render.column_table(datatype)
                self.assertIn(
                    table,
                    committed,
                    f"{datatype}: per-column table is stale — run "
                    f"`python scripts/render_data_dictionary.py`",
                )

    def test_every_schema_has_a_section(self):
        """The rendered datatype set matches the shipped schemas (no drift)."""
        shipped = {
            p.name[: -len(".schema.yaml")]
            for p in clean_io.SCHEMA_DIR.glob("*.schema.yaml")
        }
        self.assertEqual(set(render.DATATYPE_ORDER), shipped)

    def test_render_is_deterministic(self):
        """Rendering twice yields identical output."""
        self.assertEqual(render.render_document(), render.render_document())

    def test_committed_doc_matches_fresh_render(self):
        """The whole committed doc equals a fresh render (coverage included).

        Skipped when the clean tree is absent, since the coverage matrix is
        built from ``data/clean`` provenance and that tree is gitignored.
        """
        if not _clean_tree_populated():
            self.skipTest(
                "data/clean is empty — run `python scripts/regenerate_clean.py` "
                "to exercise the coverage matrix"
            )
        self.assertEqual(
            render.DOC_PATH.read_text(),
            render.render_document(),
            "data-dictionary.md is out of date — run "
            "`python scripts/render_data_dictionary.py`",
        )


if __name__ == "__main__":
    unittest.main()
