"""Monthly per-plant delivered fuel-cost lookup from EIA-923 Schedule 5.

Provides :func:`load_monthly_fuel_costs`, which returns the cached
``data/raw/_processed-legacy/eia923_monthly_fuel_costs.parquet`` produced by
:mod:`scripts.process_f923_fuel_costs`, and :func:`plant_month_price_grid`,
which reshapes that table into a ``(plant_id, fuel_group) -> (12,)`` price
array keyed lookup for the fuel-cost resolver.

A plant-month without a reported delivered cost is absent from the table
(EIA suppresses the field for many records). The resolver fills those
gaps with the existing AEO Henry Hub / coal trajectories so the dispatch
LP never sees a NaN fuel price.

Clean-data status: this per-plant EIA-923 Schedule-5 fuel-cost series is **not
yet a clean datatype** — there is no ``data/dictionary/schema`` contract for a
per-plant, per-month delivered fuel cost (the ``fuel-prices`` schema is national
hub benchmarks keyed by ``(fuel, hub, interval_start_utc)``, with no plant grain
or quantity weight). So this loader stays on the raw
``data/raw/_processed-legacy`` parquet; it is intentionally left outside the
``MARKET_SIM_USE_CLEAN`` read path. Migrating it is a contract change (a new
``fuel-costs`` / EIA-923 schema), raised rather than invented here.
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import pandas as pd

from market_sim.config.paths import PROCESSED_DIR

logger = logging.getLogger(__name__)

# Default location of the processed F923 monthly cost parquet (central registry).
EIA923_MONTHLY_COSTS_PATH: Path = PROCESSED_DIR / "eia923_monthly_fuel_costs.parquet"

# Default location of the processed F923 Page-1 generation parquet, with
# one row per ``(year, plant_id, prime_mover, fuel_type, chp)``.
EIA923_MONTHLY_GENERATION_PATH: Path = (
    PROCESSED_DIR / "eia923_monthly_generation.parquet"
)

_MONTHS_SHORT: tuple[str, ...] = (
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
)

# Number of calendar months in a year — the price grid is always 12 entries
# wide so a missing month falls back to a per-fuel default at lookup time.
_MONTHS_PER_YEAR: int = 12


def load_monthly_fuel_costs(
    path: str | Path | None = None,
) -> pd.DataFrame:
    """Return the per-plant monthly delivered fuel-cost table.

    Args:
        path: Optional override for the parquet location. ``None`` uses
            :data:`EIA923_MONTHLY_COSTS_PATH`.

    Returns:
        A DataFrame with columns ``year``, ``month``, ``plant_id``,
        ``fuel_group`` and ``price_per_mmbtu`` (delivered $/MMBtu). One
        row per ``(year, month, plant_id, fuel_group)`` quintet.

    Raises:
        FileNotFoundError: When the parquet has not yet been generated by
            :mod:`scripts.process_f923_fuel_costs`.
    """
    resolved = Path(path) if path is not None else EIA923_MONTHLY_COSTS_PATH
    if not resolved.exists():
        raise FileNotFoundError(
            f"F923 monthly fuel-cost parquet not found at {resolved!s}; "
            f"run scripts/process_f923_fuel_costs.py to generate it."
        )
    return pd.read_parquet(resolved)


def plant_month_price_grid(
    costs: pd.DataFrame,
    year: int,
    fuel_group: str,
) -> dict[int, np.ndarray]:
    """Return ``{plant_id: (12,) price array}`` for one year and fuel group.

    A plant-month without a reported price is left as NaN in its slot so
    the caller can fall back to a per-fuel default. ``fuel_group`` is the
    EIA-923 group string (e.g. ``"Natural Gas"``, ``"Coal"``,
    ``"Petroleum"``).

    Args:
        costs: The monthly cost frame from :func:`load_monthly_fuel_costs`.
        year: Calendar year to extract.
        fuel_group: EIA-923 ``FUEL_GROUP`` value to filter on.

    Returns:
        ``{plant_id: prices}``, with prices a length-12 ``float64`` array
        (index 0 = January). Plants with no reported month for the year
        are absent from the dict.
    """
    subset = costs[(costs["year"] == year) & (costs["fuel_group"] == fuel_group)]
    grid: dict[int, np.ndarray] = {}
    if subset.empty:
        return grid
    for plant_id, group in subset.groupby("plant_id", sort=False):
        prices = np.full(_MONTHS_PER_YEAR, np.nan, dtype=float)
        for _, row in group.iterrows():
            month_idx = int(row["month"]) - 1
            if 0 <= month_idx < _MONTHS_PER_YEAR:
                prices[month_idx] = float(row["price_per_mmbtu"])
        grid[int(plant_id)] = prices
    return grid


def available_years(costs: pd.DataFrame) -> set[int]:
    """Return the set of calendar years covered by the cost table."""
    return {int(y) for y in costs["year"].unique()}


def plant_state_map(costs: pd.DataFrame) -> dict[int, str]:
    """Return ``{plant_id: state}`` from the cost table's ``state`` column.

    Empty when the table predates the ``state`` column (older parquets
    built before :mod:`scripts.process_f923_fuel_costs` carried it), so the
    state-level fallback simply degrades to the zonal one.
    """
    if "state" not in costs.columns:
        return {}
    sub = costs[["plant_id", "state"]].dropna()
    return {int(p): str(s) for p, s in zip(sub["plant_id"], sub["state"]) if str(s)}


def state_month_price_grid(
    costs: pd.DataFrame,
    year: int,
    fuel_group: str,
) -> tuple[dict[str, np.ndarray], dict[str, np.ndarray]]:
    """Return per-state quantity-weighted monthly price and reporter counts.

    For one year and fuel group, aggregates every reporting plant in a
    state into a single delivered-cost series, weighting each plant-month
    by its reported ``quantity`` (MMBtu received). The companion count grid
    gives the number of distinct plants reporting in each state-month, so
    the caller can require a minimum sample before trusting the state mean
    and otherwise fall back to a broader (zonal) average.

    Args:
        costs: The monthly cost frame from :func:`load_monthly_fuel_costs`.
        year: Calendar year to extract.
        fuel_group: EIA-923 ``FUEL_GROUP`` value to filter on.

    Returns:
        ``(price, count)`` where ``price[state]`` is a length-12 array of
        quantity-weighted $/MMBtu (NaN for months no plant reported) and
        ``count[state]`` is a length-12 array of distinct-reporter counts.
    """
    price: dict[str, np.ndarray] = {}
    count: dict[str, np.ndarray] = {}
    if "state" not in costs.columns:
        return price, count
    subset = costs[
        (costs["year"] == year)
        & (costs["fuel_group"] == fuel_group)
        & (costs["state"].astype(bool))
    ]
    if subset.empty:
        return price, count
    for state, grp in subset.groupby("state", sort=False):
        wsum = np.zeros(_MONTHS_PER_YEAR, dtype=float)
        qsum = np.zeros(_MONTHS_PER_YEAR, dtype=float)
        cnt = np.zeros(_MONTHS_PER_YEAR, dtype=float)
        for _, row in grp.iterrows():
            m = int(row["month"]) - 1
            if not 0 <= m < _MONTHS_PER_YEAR:
                continue
            q = float(row["quantity"])
            wsum[m] += float(row["price_per_mmbtu"]) * q
            qsum[m] += q
            cnt[m] += 1.0
        with np.errstate(invalid="ignore", divide="ignore"):
            avg = np.where(qsum > 0.0, wsum / qsum, np.nan)
        price[str(state)] = avg
        count[str(state)] = cnt
    return price, count


def load_monthly_generation(
    path: str | Path | None = None,
) -> pd.DataFrame:
    """Return the per-plant monthly net-generation table from F923 Page 1.

    One row per ``(year, plant_id, prime_mover, fuel_type, chp)``, with
    annual ``netgen_annual_mwh`` and twelve ``netgen_<month>_mwh``
    columns. Multi-fuel plants (e.g. a coal + gas-steam co-located unit)
    keep their rows separate so a downstream consumer can bucket them
    into the model's fossil classes by fuel and prime mover.

    Args:
        path: Optional override for the parquet location. ``None`` uses
            :data:`EIA923_MONTHLY_GENERATION_PATH`.

    Raises:
        FileNotFoundError: When the parquet has not yet been generated.
    """
    resolved = Path(path) if path is not None else EIA923_MONTHLY_GENERATION_PATH
    if not resolved.exists():
        raise FileNotFoundError(
            f"F923 monthly-generation parquet not found at {resolved!s}; "
            f"run scripts/process_f923_fuel_costs.py to generate it."
        )
    return pd.read_parquet(resolved)


def monthly_netgen_columns() -> list[str]:
    """Return the twelve monthly netgen column names, in calendar order."""
    return [f"netgen_{m}_mwh" for m in _MONTHS_SHORT]


# Newest EIA-923 vintage whose monthly-generation table carries the COMPLETE
# (final-release) plant census. Vintages after it on disk are monthly early
# releases covering only the monthly-survey (large) reporters — PJM carries
# 10/8 hydro plants in 2025/2026 vs 72 in the 2024 final; NEISO 5 vs 166 —
# and years past the newest vintage have no rows at all. The forecast hydro
# path clamps its budget *shape* year (per-plant within-month shares) to this
# vintage so the fleet never silently degrades to a partial census or empties
# (docs/handoffs/nyiso-forecast-2035-2026-07-13.md finding 1); the budget
# *level* stays the EIA-930 climatology (constants.HYDRO_CLIMATOLOGY_YEARS).
# Identification: measured data vintage (rule 23 — bump only when a newer
# FINAL EIA-923 annual file lands on disk, never against a residual). Source:
# EIA Form 923 release schedule; on-disk per-year plant-census counts of the
# F923 monthly-generation extract.
EIA923_LATEST_FINAL_VINTAGE: int = 2024
