"""Monthly per-plant delivered fuel-cost lookup from EIA-923 Schedule 5.

Provides :func:`load_monthly_fuel_costs`, which returns the cached
``inputs/processed/eia923_monthly_fuel_costs.parquet`` produced by
:mod:`scripts.process_f923_fuel_costs`, and :func:`plant_month_price_grid`,
which reshapes that table into a ``(plant_id, fuel_group) -> (12,)`` price
array keyed lookup for the fuel-cost resolver.

A plant-month without a reported delivered cost is absent from the table
(EIA suppresses the field for many records). The resolver fills those
gaps with the existing AEO Henry Hub / coal trajectories so the dispatch
LP never sees a NaN fuel price.
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# Default location of the processed F923 monthly cost parquet, resolved
# relative to the repo root (this file lives at src/market_sim/data/).
EIA923_MONTHLY_COSTS_PATH: Path = (
    Path(__file__).parents[3] / "inputs" / "processed"
    / "eia923_monthly_fuel_costs.parquet"
)

# Number of calendar months in a year — the price grid is always 12 entries
# wide so a missing month falls back to a per-fuel default at lookup time.
_MONTHS_PER_YEAR: int = 12


def load_monthly_fuel_costs(
    path: str | Path | None = None,
) -> pd.DataFrame:
    """Return the per-plant monthly delivered fuel-cost table.

    Args:
        path: Optional override for the parquet location. ``None`` uses
            :data:`EIA923_MONTHLY_COSTS_PATH`.

    Returns:
        A DataFrame with columns ``year``, ``month``, ``plant_id``,
        ``fuel_group`` and ``price_per_mmbtu`` (delivered $/MMBtu). One
        row per ``(year, month, plant_id, fuel_group)`` quintet.

    Raises:
        FileNotFoundError: When the parquet has not yet been generated by
            :mod:`scripts.process_f923_fuel_costs`.
    """
    resolved = Path(path) if path is not None else EIA923_MONTHLY_COSTS_PATH
    if not resolved.exists():
        raise FileNotFoundError(
            f"F923 monthly fuel-cost parquet not found at {resolved!s}; "
            f"run scripts/process_f923_fuel_costs.py to generate it."
        )
    return pd.read_parquet(resolved)


def plant_month_price_grid(
    costs: pd.DataFrame, year: int, fuel_group: str,
) -> dict[int, np.ndarray]:
    """Return ``{plant_id: (12,) price array}`` for one year and fuel group.

    A plant-month without a reported price is left as NaN in its slot so
    the caller can fall back to a per-fuel default. ``fuel_group`` is the
    EIA-923 group string (e.g. ``"Natural Gas"``, ``"Coal"``,
    ``"Petroleum"``).

    Args:
        costs: The monthly cost frame from :func:`load_monthly_fuel_costs`.
        year: Calendar year to extract.
        fuel_group: EIA-923 ``FUEL_GROUP`` value to filter on.

    Returns:
        ``{plant_id: prices}``, with prices a length-12 ``float64`` array
        (index 0 = January). Plants with no reported month for the year
        are absent from the dict.
    """
    subset = costs[(costs["year"] == year) & (costs["fuel_group"] == fuel_group)]
    grid: dict[int, np.ndarray] = {}
    if subset.empty:
        return grid
    for plant_id, group in subset.groupby("plant_id", sort=False):
        prices = np.full(_MONTHS_PER_YEAR, np.nan, dtype=float)
        for _, row in group.iterrows():
            month_idx = int(row["month"]) - 1
            if 0 <= month_idx < _MONTHS_PER_YEAR:
                prices[month_idx] = float(row["price_per_mmbtu"])
        grid[int(plant_id)] = prices
    return grid


def available_years(costs: pd.DataFrame) -> set[int]:
    """Return the set of calendar years covered by the cost table."""
    return {int(y) for y in costs["year"].unique()}
