"""Interchange model package (created by the 3E layering fix; 3F extends it).

Created 2026-07-21 (refactor-consolidation plan §5 item 5): the unified
``InterchangeSpec`` system — per-ISO corridors, reference-price neighbors,
firm imports, seam ladders, and the interchange fleet/topology builders —
is model-layer physics, and importing it from ``config/`` inverted the
config→data→model layering. The module moved INTACT to :mod:`.spec`; the
only content change is the constants dedup (the local
``CARB_UNSPECIFIED_IMPORT_EF`` / ``_GAS_BASIS_NYISO`` copies deleted in
favour of the canonical ``config.constants`` definitions — rule 25).

Session 3F relocates ``model/transmission.py`` into this package (core.py,
import_nodes.py, per-ISO modules, registry.py per plan §5 item 6) — keep
this ``__init__`` limited to re-exports so 3F can extend it cleanly.

Compatibility contract: ``market_sim.config.interchange_config`` (the
historical import path used by src, scripts, and the tests) is a facade that
aliases itself to :mod:`.spec` via ``sys.modules``, so the historical path
and the spec module are ONE namespace object. This ``__init__`` additionally
re-exports the full spec surface so the layered
``from market_sim.model.interchange import <name>`` path works for every
name. The surface is pinned by ``tests/test_config_model_layering.py``.
"""

from __future__ import annotations

from market_sim.model.interchange.spec import (  # noqa: F401
    CAISO_CORRIDOR_ATC_SOLAR_K,
    CAISO_CORRIDOR_DIBA,
    CAISO_CORRIDOR_FLOW_PERCENTILE,
    CAISO_DAYTIME_CLEAN_HOD_MAX,
    CAISO_DAYTIME_CLEAN_HOD_MIN,
    CAISO_DAYTIME_CLEAN_TRIM_HOD_MAX,
    CAISO_DSW_DAYTIME_CLEAN_DEPTH_BY_YEAR,
    CAISO_DSW_DAYTIME_CLEAN_DEPTH_STATIC,
    CAISO_DSW_DAYTIME_CLEAN_NAME,
    CAISO_DSW_DAYTIME_CLEAN_TRIM_DEPTH_BY_YEAR,
    CAISO_DSW_DAYTIME_CLEAN_TRIM_DEPTH_STATIC,
    CAISO_DSW_OVERNIGHT_CLEAN_DEPTH_BY_YEAR,
    CAISO_DSW_OVERNIGHT_CLEAN_DEPTH_STATIC,
    CAISO_DSW_OVERNIGHT_CLEAN_NAME,
    CAISO_DSW_SURPLUS_CLEAN_DEPTH_BY_YEAR,
    CAISO_DSW_SURPLUS_CLEAN_DEPTH_STATIC,
    CAISO_DSW_SURPLUS_CLEAN_NAME,
    CAISO_DSW_SURPLUS_REMOTE_VOM,
    CAISO_FIRM_IMPORT_SHAPE_PERCENTILE,
    CAISO_IMPORT_DELIVERY_BASIS,
    CAISO_IMPORT_TRANCHE_HUB,
    CAISO_OVERNIGHT_CLEAN_HOD_MAX,
    CAISO_PER_HUB_IMPORT_ZONES,
    CAISO_PER_HUB_NEIGHBORS,
    CARB_UNSPECIFIED_IMPORT_EF,
    CaisoHubNeighbor,
    Corridor,
    EXPORT_TRANCHES,
    EXPORT_TRANCHES_BY_YEAR,
    EXTERNAL_SIMULTANEOUS_LIMITS,
    FirmImport,
    Generator,
    IMPORT_EFORD,
    IMPORT_NODE_LINKS,
    IMPORT_TRANCHES,
    IMPORT_TRANCHES_BY_YEAR,
    IMPORT_TRANCHE_EF,
    IMPORT_ZONE,
    INTERFACE_NEIGHBORS,
    InterchangeSpec,
    MISO_FIRM_IMPORT_DEFAULT_ISOS,
    MISO_MANITOBA_FIRM_IMPORT_FLOOR_FRAC,
    MISO_MANITOBA_FIRM_IMPORT_MW,
    MISO_MANITOBA_FIRM_IMPORT_MW_BY_YEAR,
    MISO_MANITOBA_FIRM_IMPORT_NAME,
    MISO_MANITOBA_FIRM_IMPORT_OFFER,
    MISO_MANITOBA_FIRM_IMPORT_ZONE,
    MISO_MANITOBA_SEAM_SPEC,
    MISO_PJM_BORDER_HR_BY_YEAR,
    MISO_SEAM_DIBA,
    MISO_SEAM_LADDER_BY_YEAR,
    NYISO_FIRM_IMPORT_FLOOR_FRAC,
    NYISO_IMPORT_RECON_BAND_FRAC,
    NeighborInterface,
    PJM_SEAM_LADDER_BY_YEAR,
    PJM_SEAM_TIE,
    PRICED_INTERCHANGE_DEFAULT_ISOS,
    REFERENCE_PRICE_DEFAULT_ISOS,
    ReconciliationBand,
    WECC_EXPORT_CAP_MW,
    WECC_IMPORT_EFORD,
    WECC_IMPORT_TRANCHES,
    apply_interchange_topology,
    build_interchange_fleet,
    get_interchange_spec,
    resolve_miso_firm_imports,
    resolve_miso_manitoba_firm_import_mw,
    resolve_priced_interchange,
    _build_static_tranche_gens as _build_static_tranche_gens,
)

__all__ = [
    "CAISO_CORRIDOR_ATC_SOLAR_K",
    "CAISO_CORRIDOR_DIBA",
    "CAISO_CORRIDOR_FLOW_PERCENTILE",
    "CAISO_DAYTIME_CLEAN_HOD_MAX",
    "CAISO_DAYTIME_CLEAN_HOD_MIN",
    "CAISO_DAYTIME_CLEAN_TRIM_HOD_MAX",
    "CAISO_DSW_DAYTIME_CLEAN_DEPTH_BY_YEAR",
    "CAISO_DSW_DAYTIME_CLEAN_DEPTH_STATIC",
    "CAISO_DSW_DAYTIME_CLEAN_NAME",
    "CAISO_DSW_DAYTIME_CLEAN_TRIM_DEPTH_BY_YEAR",
    "CAISO_DSW_DAYTIME_CLEAN_TRIM_DEPTH_STATIC",
    "CAISO_DSW_OVERNIGHT_CLEAN_DEPTH_BY_YEAR",
    "CAISO_DSW_OVERNIGHT_CLEAN_DEPTH_STATIC",
    "CAISO_DSW_OVERNIGHT_CLEAN_NAME",
    "CAISO_DSW_SURPLUS_CLEAN_DEPTH_BY_YEAR",
    "CAISO_DSW_SURPLUS_CLEAN_DEPTH_STATIC",
    "CAISO_DSW_SURPLUS_CLEAN_NAME",
    "CAISO_DSW_SURPLUS_REMOTE_VOM",
    "CAISO_FIRM_IMPORT_SHAPE_PERCENTILE",
    "CAISO_IMPORT_DELIVERY_BASIS",
    "CAISO_IMPORT_TRANCHE_HUB",
    "CAISO_OVERNIGHT_CLEAN_HOD_MAX",
    "CAISO_PER_HUB_IMPORT_ZONES",
    "CAISO_PER_HUB_NEIGHBORS",
    "CARB_UNSPECIFIED_IMPORT_EF",
    "CaisoHubNeighbor",
    "Corridor",
    "EXPORT_TRANCHES",
    "EXPORT_TRANCHES_BY_YEAR",
    "EXTERNAL_SIMULTANEOUS_LIMITS",
    "FirmImport",
    "Generator",
    "IMPORT_EFORD",
    "IMPORT_NODE_LINKS",
    "IMPORT_TRANCHES",
    "IMPORT_TRANCHES_BY_YEAR",
    "IMPORT_TRANCHE_EF",
    "IMPORT_ZONE",
    "INTERFACE_NEIGHBORS",
    "InterchangeSpec",
    "MISO_FIRM_IMPORT_DEFAULT_ISOS",
    "MISO_MANITOBA_FIRM_IMPORT_FLOOR_FRAC",
    "MISO_MANITOBA_FIRM_IMPORT_MW",
    "MISO_MANITOBA_FIRM_IMPORT_MW_BY_YEAR",
    "MISO_MANITOBA_FIRM_IMPORT_NAME",
    "MISO_MANITOBA_FIRM_IMPORT_OFFER",
    "MISO_MANITOBA_FIRM_IMPORT_ZONE",
    "MISO_MANITOBA_SEAM_SPEC",
    "MISO_PJM_BORDER_HR_BY_YEAR",
    "MISO_SEAM_DIBA",
    "MISO_SEAM_LADDER_BY_YEAR",
    "NYISO_FIRM_IMPORT_FLOOR_FRAC",
    "NYISO_IMPORT_RECON_BAND_FRAC",
    "NeighborInterface",
    "PJM_SEAM_LADDER_BY_YEAR",
    "PJM_SEAM_TIE",
    "PRICED_INTERCHANGE_DEFAULT_ISOS",
    "REFERENCE_PRICE_DEFAULT_ISOS",
    "ReconciliationBand",
    "WECC_EXPORT_CAP_MW",
    "WECC_IMPORT_EFORD",
    "WECC_IMPORT_TRANCHES",
    "apply_interchange_topology",
    "build_interchange_fleet",
    "get_interchange_spec",
    "resolve_miso_firm_imports",
    "resolve_miso_manitoba_firm_import_mw",
    "resolve_priced_interchange",
]
