"""Interchange model package (created by the 3E layering fix; 3F extends it).

Created 2026-07-21 (refactor-consolidation plan §5 item 5): the unified
``InterchangeSpec`` system — per-ISO corridors, reference-price neighbors,
firm imports, seam ladders, and the interchange fleet/topology builders —
is model-layer physics, and importing it from ``config/`` inverted the
config→data→model layering. The module moved INTACT to :mod:`.spec`; the
only content change is the constants dedup (the local
``CARB_UNSPECIFIED_IMPORT_EF`` / ``_GAS_BASIS_NYISO`` copies deleted in
favour of the canonical ``config.constants`` definitions — rule 25).

Session 3F (plan §5 item 6) relocated ``model/transmission.py`` into this
package: :mod:`.core` (incidence/TTC/interface groups + the reliability-floor
engine), :mod:`.import_nodes` (priced import/export nodes + the generic
reference-price seam), the per-ISO modules :mod:`.caiso` / :mod:`.miso` /
:mod:`.pjm` / :mod:`.nyiso` / :mod:`.neiso`, and :mod:`.registry` (the
ISO → injection-step registry consumed by ``apply_interchange_injections``).
``market_sim.model.transmission`` is now a second alias facade of THIS
package (the ``model/capacity.py`` pattern), so the historical transmission
path and this package are ONE namespace object too; its surface is pinned by
``tests/test_transmission_facade.py``. This ``__init__`` stays limited to
re-exports.

Compatibility contract: ``market_sim.config.interchange_config`` (the
historical import path used by src, scripts, and the tests) is a facade that
aliases itself to :mod:`.spec` via ``sys.modules``, so the historical path
and the spec module are ONE namespace object. This ``__init__`` additionally
re-exports the full spec surface so the layered
``from market_sim.model.interchange import <name>`` path works for every
name. The surface is pinned by ``tests/test_config_model_layering.py``.
"""

from __future__ import annotations

from market_sim.model.interchange.spec import (  # noqa: F401
    CAISO_CORRIDOR_ATC_SOLAR_K,
    CAISO_CORRIDOR_DIBA,
    CAISO_CORRIDOR_FLOW_PERCENTILE,
    CAISO_DAYTIME_CLEAN_HOD_MAX,
    CAISO_DAYTIME_CLEAN_HOD_MIN,
    CAISO_DAYTIME_CLEAN_TRIM_HOD_MAX,
    CAISO_DSW_DAYTIME_CLEAN_DEPTH_BY_YEAR,
    CAISO_DSW_DAYTIME_CLEAN_DEPTH_STATIC,
    CAISO_DSW_DAYTIME_CLEAN_NAME,
    CAISO_DSW_DAYTIME_CLEAN_TRIM_DEPTH_BY_YEAR,
    CAISO_DSW_DAYTIME_CLEAN_TRIM_DEPTH_STATIC,
    CAISO_DSW_OVERNIGHT_CLEAN_DEPTH_BY_YEAR,
    CAISO_DSW_OVERNIGHT_CLEAN_DEPTH_STATIC,
    CAISO_DSW_OVERNIGHT_CLEAN_NAME,
    CAISO_DSW_SURPLUS_CLEAN_DEPTH_BY_YEAR,
    CAISO_DSW_SURPLUS_CLEAN_DEPTH_STATIC,
    CAISO_DSW_SURPLUS_CLEAN_NAME,
    CAISO_DSW_SURPLUS_REMOTE_VOM,
    CAISO_FIRM_IMPORT_SHAPE_PERCENTILE,
    CAISO_IMPORT_DELIVERY_BASIS,
    CAISO_IMPORT_TRANCHE_HUB,
    CAISO_OVERNIGHT_CLEAN_HOD_MAX,
    CAISO_PER_HUB_IMPORT_ZONES,
    CAISO_PER_HUB_NEIGHBORS,
    CARB_UNSPECIFIED_IMPORT_EF,
    CaisoHubNeighbor,
    Corridor,
    EXPORT_TRANCHES,
    EXPORT_TRANCHES_BY_YEAR,
    EXTERNAL_SIMULTANEOUS_LIMITS,
    FirmImport,
    Generator,
    IMPORT_EFORD,
    IMPORT_NODE_LINKS,
    IMPORT_TRANCHES,
    IMPORT_TRANCHES_BY_YEAR,
    IMPORT_TRANCHE_EF,
    IMPORT_ZONE,
    INTERFACE_NEIGHBORS,
    InterchangeSpec,
    MISO_FIRM_IMPORT_DEFAULT_ISOS,
    MISO_MANITOBA_FIRM_IMPORT_FLOOR_FRAC,
    MISO_MANITOBA_FIRM_IMPORT_MW,
    MISO_MANITOBA_FIRM_IMPORT_MW_BY_YEAR,
    MISO_MANITOBA_FIRM_IMPORT_NAME,
    MISO_MANITOBA_FIRM_IMPORT_OFFER,
    MISO_MANITOBA_FIRM_IMPORT_ZONE,
    MISO_MANITOBA_SEAM_SPEC,
    MISO_PJM_BORDER_HR_BY_YEAR,
    MISO_SEAM_DIBA,
    MISO_SEAM_LADDER_BY_YEAR,
    NYISO_FIRM_IMPORT_FLOOR_FRAC,
    NYISO_IMPORT_RECON_BAND_FRAC,
    NeighborInterface,
    PJM_SEAM_LADDER_BY_YEAR,
    PJM_SEAM_TIE,
    PRICED_INTERCHANGE_DEFAULT_ISOS,
    REFERENCE_PRICE_DEFAULT_ISOS,
    ReconciliationBand,
    WECC_EXPORT_CAP_MW,
    WECC_IMPORT_EFORD,
    WECC_IMPORT_TRANCHES,
    apply_interchange_topology,
    build_interchange_fleet,
    get_interchange_spec,
    resolve_miso_firm_imports,
    resolve_miso_manitoba_firm_import_mw,
    resolve_priced_interchange,
    _build_static_tranche_gens as _build_static_tranche_gens,
)

# --- Session 3F: the relocated model/transmission.py surface. Submodule
# order matters: spec (above) first, then core/import_nodes before the
# per-ISO modules that import from them, registry last. Privates are
# re-exported deliberately (self-aliased) — they are part of the historical
# transmission facade surface (script/test importers; see
# tests/test_transmission_facade.py). ---
from market_sim.model.interchange.core import (  # noqa: F401
    _bridge_flagged_runs as _bridge_flagged_runs,
    _distribute_group_floor as _distribute_group_floor,
    build_incidence_matrix,
    build_interface_groups,
    get_link_bidirectional_array,
    get_link_flow_cost_array,
    get_ttc_array,
    inject_reliability_floor,
)
from market_sim.model.interchange.import_nodes import (  # noqa: F401
    _inject_seam_ladder as _inject_seam_ladder,
    _REF_EXPORT_MARK as _REF_EXPORT_MARK,
    _REF_IMPORT_MARK as _REF_IMPORT_MARK,
    apply_deliverability_seam_limit,
    apply_reference_price_seam_injections,
    build_export_sinks,
    build_import_generators,
    build_reference_price_node,
    extend_with_import_node,
    inject_interchange_shape,
    inject_reference_price_firm_export,
    inject_reference_price_firm_import,
    inject_reference_price_mc,
    wecc_border_carbon_adder,
)
from market_sim.model.interchange.caiso import (  # noqa: F401
    _CAISO_BIDIR_EXPORT_NAME as _CAISO_BIDIR_EXPORT_NAME,
    _caiso_corridor_export_cap_mw as _caiso_corridor_export_cap_mw,
    _caiso_corridor_import_ttc_mw as _caiso_corridor_import_ttc_mw,
    _CAISO_CORRIDOR_LINK_TO as _CAISO_CORRIDOR_LINK_TO,
    _CAISO_HUB_EXPORT_TRANCHES as _CAISO_HUB_EXPORT_TRANCHES,
    _CAISO_IMPORT_COUPLE_HR as _CAISO_IMPORT_COUPLE_HR,
    _caiso_import_tranche_of as _caiso_import_tranche_of,
    _CAISO_LOCAL_IMPORT_LINKS as _CAISO_LOCAL_IMPORT_LINKS,
    _CAISO_PER_HUB_EXPORT_PREFIX as _CAISO_PER_HUB_EXPORT_PREFIX,
    _CAISO_SOLAR_SHAPE_EXPORT_TRANCHES as _CAISO_SOLAR_SHAPE_EXPORT_TRANCHES,
    _CAISO_SOLAR_SHAPE_TRANCHES as _CAISO_SOLAR_SHAPE_TRANCHES,
    apply_caiso_asymmetric_path_limits,
    apply_caiso_local_import_limits,
    apply_caiso_seam_injections,
    build_caiso_bidir_intertie,
    build_caiso_corridor_flow_groups,
    build_caiso_per_hub_intertie,
    build_wecc_export_sink,
    build_wecc_import_generators,
    CAISO_BIDIR_EXPORT_CAP_MW,
    CAISO_BIDIR_IMPORT_CAP_MW,
    CAISO_FIRM_IMPORT_TRANCHES,
    CAISO_GAS_FLOOR_HOURS,
    CAISO_INTERTIE_TIEBREAK_EPS,
    CAISO_PATH_DIRECTIONAL_RATINGS,
    caiso_solar_deliverability_derate,
    forward_corridor_atc_envelope,
    forward_corridor_interface_groups,
    inject_caiso_bidir_intertie_prices,
    inject_caiso_dsw_daytime_clean,
    inject_caiso_dsw_overnight_clean,
    inject_caiso_dsw_surplus_clean,
    inject_caiso_export_hub_prices,
    inject_caiso_firm_import_selfschedule,
    inject_caiso_firm_import_shape,
    inject_caiso_gas_commitment_floor,
    inject_caiso_import_gas_coupling,
    inject_caiso_import_hub_prices,
    inject_caiso_import_solar_shape,
    inject_caiso_per_hub_intertie_prices,
    inject_caiso_per_hub_reference_prices,
    split_caiso_import_node_per_hub,
)
from market_sim.model.interchange.miso import (  # noqa: F401
    _miso_firm_import_uid as _miso_firm_import_uid,
    _miso_midwest_internal as _miso_midwest_internal,
    _MISO_MONTH_TO_SEASON as _MISO_MONTH_TO_SEASON,
    _MONTH_HOURS as _MONTH_HOURS,
    apply_miso_firm_import_injections,
    apply_miso_rdt_tcdc,
    apply_miso_zonal_loss_links,
    build_miso_deliverability_groups,
    build_miso_firm_imports,
    build_miso_link_loss,
    inject_miso_firm_imports,
    inject_miso_pjm_lmp_import_prices,
    inject_miso_seam_flow_limit,
    inject_miso_seam_ladder_prices,
    MISO_LOSS_LINK_TIEBREAK_EPS,
    split_miso_south_external_node,
)
from market_sim.model.interchange.pjm import (  # noqa: F401
    build_pjm_east_interface_cut_groups,
    build_pjm_external_flow_groups,
    inject_pjm_seam_flow_limit,
    inject_pjm_seam_ladder_prices,
    PJM_EAST_CUT_LINKS,
)
from market_sim.model.interchange.nyiso import (  # noqa: F401
    _dispatchable_thermal_codes as _dispatchable_thermal_codes,
    _NYISO_HUB_EXPORT_TRANCHE as _NYISO_HUB_EXPORT_TRANCHE,
    _NYISO_HUB_IMPORT_TRANCHE_NEIGHBOR as _NYISO_HUB_IMPORT_TRANCHE_NEIGHBOR,
    _NYISO_HUB_SCARCITY_TRANCHE as _NYISO_HUB_SCARCITY_TRANCHE,
    apply_nyiso_firm_import_injections,
    apply_nyiso_li_tsl_import_cap,
    apply_nyiso_nyc_tsl_import_cap,
    build_import_node_reconciliation,
    inject_nyiso_firm_imports,
    inject_nyiso_import_hub_prices,
    inject_nyiso_local_selfsupply,
    NYISO_IMPORT_HUB_HURDLE,
    NYISO_SELFSUPPLY_FLOOR_HOURS,
)
from market_sim.model.interchange.neiso import (  # noqa: F401
    inject_neiso_gas_coldsnap_derate,
    NEISO_COLDSNAP_FLOOR_HOURS,
    NEISO_GAS_DERATE_GROUPS,
)
from market_sim.model.interchange.registry import (  # noqa: F401
    apply_interchange_injections,
    INTERCHANGE_INJECTIONS,
)

# The historical model/transmission.py facade passthroughs: names it imported
# at module level and therefore re-exported. Kept resolvable here so every
# pre-split ``from market_sim.model.transmission import <name>`` keeps
# working. Canonical homes unchanged (TransferLink stays DEFINED at
# config.iso_configs — pickle identity, tests/test_persisted_identity.py).
from market_sim.config.constants import (  # noqa: F401
    MISO_RDT_CONTRACT_N_TO_S_MW,
    MISO_RDT_CONTRACT_S_TO_N_MW,
    MISO_RDT_DEFAULT_DERATE_FRAC,
    MISO_RDT_TCDC_STEP1_PRICE,
    MISO_RDT_TCDC_STEP2_PRICE,
    MISO_RDT_TCDC_STEP2_START_FRAC,
    MISO_RPE_DEMAND_VALUE,
    MISO_SOUTH_EXTERNAL_ZONE,
    NYISO_LOCAL_SELFSUPPLY_FRAC,
)
from market_sim.config.iso_configs import (  # noqa: F401
    InterfaceLimit,
    ISOConfig,
    TransferLink,
    Zone,
)
from market_sim.data.floor_mechanisms import (  # noqa: F401
    ensure_mechanism,
    MECH_CAISO_GAS_COMMITMENT_FLOOR,
    MECH_FIRM_IMPORT,
    MECH_NYISO_SELFSUPPLY,
    MECH_RELIABILITY_FLOOR,
)

__all__ = [
    "CAISO_BIDIR_EXPORT_CAP_MW",
    "CAISO_BIDIR_IMPORT_CAP_MW",
    "CAISO_CORRIDOR_ATC_SOLAR_K",
    "CAISO_CORRIDOR_DIBA",
    "CAISO_CORRIDOR_FLOW_PERCENTILE",
    "CAISO_DAYTIME_CLEAN_HOD_MAX",
    "CAISO_DAYTIME_CLEAN_HOD_MIN",
    "CAISO_DAYTIME_CLEAN_TRIM_HOD_MAX",
    "CAISO_DSW_DAYTIME_CLEAN_DEPTH_BY_YEAR",
    "CAISO_DSW_DAYTIME_CLEAN_DEPTH_STATIC",
    "CAISO_DSW_DAYTIME_CLEAN_NAME",
    "CAISO_DSW_DAYTIME_CLEAN_TRIM_DEPTH_BY_YEAR",
    "CAISO_DSW_DAYTIME_CLEAN_TRIM_DEPTH_STATIC",
    "CAISO_DSW_OVERNIGHT_CLEAN_DEPTH_BY_YEAR",
    "CAISO_DSW_OVERNIGHT_CLEAN_DEPTH_STATIC",
    "CAISO_DSW_OVERNIGHT_CLEAN_NAME",
    "CAISO_DSW_SURPLUS_CLEAN_DEPTH_BY_YEAR",
    "CAISO_DSW_SURPLUS_CLEAN_DEPTH_STATIC",
    "CAISO_DSW_SURPLUS_CLEAN_NAME",
    "CAISO_DSW_SURPLUS_REMOTE_VOM",
    "CAISO_FIRM_IMPORT_SHAPE_PERCENTILE",
    "CAISO_FIRM_IMPORT_TRANCHES",
    "CAISO_GAS_FLOOR_HOURS",
    "CAISO_IMPORT_DELIVERY_BASIS",
    "CAISO_IMPORT_TRANCHE_HUB",
    "CAISO_INTERTIE_TIEBREAK_EPS",
    "CAISO_OVERNIGHT_CLEAN_HOD_MAX",
    "CAISO_PATH_DIRECTIONAL_RATINGS",
    "CAISO_PER_HUB_IMPORT_ZONES",
    "CAISO_PER_HUB_NEIGHBORS",
    "CARB_UNSPECIFIED_IMPORT_EF",
    "CaisoHubNeighbor",
    "Corridor",
    "EXPORT_TRANCHES",
    "EXPORT_TRANCHES_BY_YEAR",
    "EXTERNAL_SIMULTANEOUS_LIMITS",
    "FirmImport",
    "Generator",
    "IMPORT_EFORD",
    "IMPORT_NODE_LINKS",
    "IMPORT_TRANCHES",
    "IMPORT_TRANCHES_BY_YEAR",
    "IMPORT_TRANCHE_EF",
    "IMPORT_ZONE",
    "INTERCHANGE_INJECTIONS",
    "INTERFACE_NEIGHBORS",
    "ISOConfig",
    "InterchangeSpec",
    "InterfaceLimit",
    "MECH_CAISO_GAS_COMMITMENT_FLOOR",
    "MECH_FIRM_IMPORT",
    "MECH_NYISO_SELFSUPPLY",
    "MECH_RELIABILITY_FLOOR",
    "MISO_FIRM_IMPORT_DEFAULT_ISOS",
    "MISO_LOSS_LINK_TIEBREAK_EPS",
    "MISO_MANITOBA_FIRM_IMPORT_FLOOR_FRAC",
    "MISO_MANITOBA_FIRM_IMPORT_MW",
    "MISO_MANITOBA_FIRM_IMPORT_MW_BY_YEAR",
    "MISO_MANITOBA_FIRM_IMPORT_NAME",
    "MISO_MANITOBA_FIRM_IMPORT_OFFER",
    "MISO_MANITOBA_FIRM_IMPORT_ZONE",
    "MISO_MANITOBA_SEAM_SPEC",
    "MISO_PJM_BORDER_HR_BY_YEAR",
    "MISO_RDT_CONTRACT_N_TO_S_MW",
    "MISO_RDT_CONTRACT_S_TO_N_MW",
    "MISO_RDT_DEFAULT_DERATE_FRAC",
    "MISO_RDT_TCDC_STEP1_PRICE",
    "MISO_RDT_TCDC_STEP2_PRICE",
    "MISO_RDT_TCDC_STEP2_START_FRAC",
    "MISO_RPE_DEMAND_VALUE",
    "MISO_SEAM_DIBA",
    "MISO_SEAM_LADDER_BY_YEAR",
    "MISO_SOUTH_EXTERNAL_ZONE",
    "NEISO_COLDSNAP_FLOOR_HOURS",
    "NEISO_GAS_DERATE_GROUPS",
    "NYISO_FIRM_IMPORT_FLOOR_FRAC",
    "NYISO_IMPORT_HUB_HURDLE",
    "NYISO_IMPORT_RECON_BAND_FRAC",
    "NYISO_LOCAL_SELFSUPPLY_FRAC",
    "NYISO_SELFSUPPLY_FLOOR_HOURS",
    "NeighborInterface",
    "PJM_EAST_CUT_LINKS",
    "PJM_SEAM_LADDER_BY_YEAR",
    "PJM_SEAM_TIE",
    "PRICED_INTERCHANGE_DEFAULT_ISOS",
    "REFERENCE_PRICE_DEFAULT_ISOS",
    "ReconciliationBand",
    "TransferLink",
    "WECC_EXPORT_CAP_MW",
    "WECC_IMPORT_EFORD",
    "WECC_IMPORT_TRANCHES",
    "Zone",
    "apply_caiso_asymmetric_path_limits",
    "apply_caiso_local_import_limits",
    "apply_caiso_seam_injections",
    "apply_deliverability_seam_limit",
    "apply_interchange_injections",
    "apply_interchange_topology",
    "apply_miso_firm_import_injections",
    "apply_miso_rdt_tcdc",
    "apply_miso_zonal_loss_links",
    "apply_nyiso_firm_import_injections",
    "apply_nyiso_li_tsl_import_cap",
    "apply_nyiso_nyc_tsl_import_cap",
    "apply_reference_price_seam_injections",
    "build_caiso_bidir_intertie",
    "build_caiso_corridor_flow_groups",
    "build_caiso_per_hub_intertie",
    "build_export_sinks",
    "build_import_generators",
    "build_import_node_reconciliation",
    "build_incidence_matrix",
    "build_interchange_fleet",
    "build_interface_groups",
    "build_miso_deliverability_groups",
    "build_miso_firm_imports",
    "build_miso_link_loss",
    "build_pjm_east_interface_cut_groups",
    "build_pjm_external_flow_groups",
    "build_reference_price_node",
    "build_wecc_export_sink",
    "build_wecc_import_generators",
    "caiso_solar_deliverability_derate",
    "ensure_mechanism",
    "extend_with_import_node",
    "forward_corridor_atc_envelope",
    "forward_corridor_interface_groups",
    "get_interchange_spec",
    "get_link_bidirectional_array",
    "get_link_flow_cost_array",
    "get_ttc_array",
    "inject_caiso_bidir_intertie_prices",
    "inject_caiso_dsw_daytime_clean",
    "inject_caiso_dsw_overnight_clean",
    "inject_caiso_dsw_surplus_clean",
    "inject_caiso_export_hub_prices",
    "inject_caiso_firm_import_selfschedule",
    "inject_caiso_firm_import_shape",
    "inject_caiso_gas_commitment_floor",
    "inject_caiso_import_gas_coupling",
    "inject_caiso_import_hub_prices",
    "inject_caiso_import_solar_shape",
    "inject_caiso_per_hub_intertie_prices",
    "inject_caiso_per_hub_reference_prices",
    "inject_interchange_shape",
    "inject_miso_firm_imports",
    "inject_miso_pjm_lmp_import_prices",
    "inject_miso_seam_flow_limit",
    "inject_miso_seam_ladder_prices",
    "inject_neiso_gas_coldsnap_derate",
    "inject_nyiso_firm_imports",
    "inject_nyiso_import_hub_prices",
    "inject_nyiso_local_selfsupply",
    "inject_pjm_seam_flow_limit",
    "inject_pjm_seam_ladder_prices",
    "inject_reference_price_firm_export",
    "inject_reference_price_firm_import",
    "inject_reference_price_mc",
    "inject_reliability_floor",
    "resolve_miso_firm_imports",
    "resolve_miso_manitoba_firm_import_mw",
    "resolve_priced_interchange",
    "split_caiso_import_node_per_hub",
    "split_miso_south_external_node",
    "wecc_border_carbon_adder",
]
