"""Emit the scorer's rubric constants as a generated dashboard data file.

The Run Explorer (``docs/codebase-site/js/backcast-runs.js``) colours its
generation-mix tables with the SAME C1 tolerance bands and the SAME gas/coal
class membership the machine scorer gates on. Until Wave 5C those numbers were
hand-typed into the page behind "mirrors calibration_verdict.X exactly"
comments — a comment-synced copy, i.e. a drift trap: nothing failed when the
scorer moved (and it has moved: the 2026-07-02 C1 re-balance loosened
0.01/5/1.5 to 0.02/8/3.0 in both places by hand).

This module removes the copy. It reads ``scripts/calibration_verdict.py``'s own
module constants and renders them as
``frontend/data/backcast/rubric-consts.js``::

    window.BC=window.BC||{};window.BC.rubricConsts={...};

which ``docs/codebase-site/js/bc-data.js`` loads alongside ``benchmark.js`` /
``completeness.js`` and hands to the page. A rubric change now reaches the
dashboard by regenerating this file, never by editing JS.

Byte-determinism (dashboard contract §8, CLAUDE.md rule 13): the payload is
``json.dumps(..., sort_keys=True)`` over plain scalars/lists, so unchanged
scorer constants re-render to identical bytes and concurrent calibration
sessions running ``build_manifest.py`` never conflict on this file. The
``FUELMIX_EXCLUDED`` frozenset is emitted ``sorted()`` for the same reason —
set iteration order is not a wire format.

STDLIB-ONLY (json + pathlib), and ``calibration_verdict`` is imported lazily
inside the builder so importing this module costs nothing and ``scripts.lib``
carries no module-level dependency on a top-level script. Both matter: the
Pages deploy runs the writer on a bare ``python3`` with no installed deps.

Generated file, never hand-edited: ``scripts/build_manifest.py`` writes it at
deploy time (and on the local preview refresh), exactly like ``manifest.js``.
"""

from __future__ import annotations

import json
from pathlib import Path

# scripts/lib/rubric_consts.py -> <repo>/scripts/lib -> <repo>
REPO = Path(__file__).resolve().parent.parent.parent

#: Basename of the generated file inside ``frontend/data/backcast/``.
FILENAME = "rubric-consts.js"

#: Emitted verbatim as the file's first line so a reader (or a grep) sees at
#: once that the bytes are generated. Paired with the ``.gitattributes``
#: ``linguist-generated`` marking on the committed preview copy.
HEADER = (
    "// GENERATED by scripts/build_manifest.py via scripts/lib/rubric_consts.py "
    "from scripts/calibration_verdict.py — do not edit.\n"
)


def rubric_consts() -> dict:
    """Return the scorer constants the backcast pages consume.

    Every value is read from ``scripts.calibration_verdict``'s module namespace,
    so this function is the only place the JS-side names are bound to Python
    ones. Keys are the JS spellings used by ``window.BC.rubricConsts``.
    """
    from scripts import calibration_verdict as cv  # lazy: see module docstring
    from scripts.lib import holdout_policy as hp  # stdlib-only, safe at deploy

    return {
        # Provenance, for the page's own diagnostics (never a gate).
        "rubricVersion": cv.RUBRIC_VERSION,
        "source": "scripts/calibration_verdict.py",
        # C1 fuel-mix bands: a class passes iff its volume miss is within
        # min(max(volLoadFrac x ISO load, volGenFloorFrac x actual total gen),
        # volCapTWh) AND its generation share is within sharePP percentage
        # points. The gen-floor term is the rubric v3.4 owner amendment
        # (2026-08-18); it is FUELMIX_SHARE_PP/100 by construction (the share
        # leg's own mix-materiality, no new constant), exported explicitly so
        # the JS never re-derives it.
        "fuelmixVolLoadFrac": cv.FUELMIX_VOL_LOAD_FRAC,
        "fuelmixVolGenFloorFrac": cv.FUELMIX_SHARE_PP / 100.0,
        "fuelmixVolCapTWh": cv.FUELMIX_VOL_CAP_TWH,
        "fuelmixSharePP": cv.FUELMIX_SHARE_PP,
        # C1 gate membership. Declaration order is preserved (the scorer emits
        # its per-class records in this order); the page only tests membership.
        "gasClasses": list(cv.GAS_CLASSES),
        "coalClasses": list(cv.COAL_CLASSES),
        # Coal FAMILY-total keys: the subclasses plus the legacy bare-COAL row
        # a payload committed before COAL-SUB (2026-09-25) may carry — read for
        # the family total only, never gated as a class.
        "coalFamilyKeys": list(cv.COAL_FAMILY_KEYS),
        # frozenset -> sorted list: set order is not a wire format.
        "fuelmixExcluded": sorted(cv.FUELMIX_EXCLUDED),
        # Non-fossil fuels whose actual comes from EIA-930, not 923.
        "nonfossilFuels": list(cv.NONFOSSIL_FUELS),
        # Rule-22 holdout tiers, straight from scripts/lib/holdout_policy.py.
        # The Run Explorer labels a held-out year's tier (and its caveat) in the
        # year selector; without this it would need the year lists typed into
        # JS, which is the same drift trap the C1 bands above were moved out of.
        # Consumers MUST fail closed to "locked_test" for a year in none of the
        # three sets, exactly as holdout_policy.tier_for_year does.
        "holdoutTiers": {
            hp.TIER_TRAIN: sorted(hp.CALIBRATION_YEARS),
            hp.TIER_VALIDATION: sorted(hp.VALIDATION_YEARS),
            hp.TIER_LOCKED: sorted(hp.LOCKED_TEST_YEARS),
        },
    }


def render_js(consts: dict | None = None) -> str:
    """Render the ``window.BC.rubricConsts`` assignment (byte-deterministic)."""
    payload = json.dumps(rubric_consts() if consts is None else consts, sort_keys=True)
    return HEADER + "window.BC=window.BC||{};window.BC.rubricConsts=" + payload + ";"


def write_rubric_consts_js(out_dir: Path) -> Path:
    """Write ``rubric-consts.js`` into ``out_dir`` and return its path."""
    path = Path(out_dir) / FILENAME
    path.write_text(render_js())
    return path
