"""Render the F1 census JSONs into ``census_summary.md`` (zero LP).

Usage::

    uv run python docs/handoffs/f1/summarize.py
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ISOS = ("CAISO", "ERCOT", "MISO", "NEISO", "NWPP", "NYISO", "PJM", "SOCO", "SPP")
YEARS = [str(y) for y in range(2019, 2026)]


def _load(name: str) -> dict:
    return json.loads((HERE / name).read_text())["isos"]


def _pct(v) -> str:
    return "—" if v is None else f"{100 * v:.1f}"


def main() -> int:
    """Write the summary markdown."""
    pre_audit = _load("census_pre_audit.json")
    pre = _load("census_pre_tracked.json")
    post_eg = _load("census_post_egrid_tracked.json")
    post = _load("census_post_default_tracked.json")
    out: list[str] = ["# F1 census summary (zero LP)", ""]
    out += [
        "Generated by `docs/handoffs/f1/summarize.py` from the four census JSONs "
        "beside it (`census.py`). `bins` = the audit's §3a heuristic (loaded heat "
        "rate equals a `HEAT_RATE_BINS` value); `null` = the EXACT measure (the "
        "plant's EIA-860 source row carries no joined eGRID heat rate). Units: % "
        "of thermal nameplate (coal, gas_cc, gas_ct, gas_st, oil). Source per "
        "year = the post-F1 backcast default (vintage_<Y> for 2019-2024, the "
        "canonical snapshot for 2025).",
        "",
        "Acceptance bar (item 5): the pre-F1 **vintage_2023** share (audit §3a "
        "'vintage_2023' column), per ISO.",
        "",
        "## §3a — class-table share of thermal nameplate, pre -> post (exact `null` measure)",
        "",
        "| ISO | bar (pre v2023 null) | " + " | ".join(YEARS) + " | max post | pass |",
        "|---|---|" + "---|" * len(YEARS) + "---|---|",
    ]
    for iso in ISOS:
        bar = pre_audit[iso]["operable"]["vintage_2023"]["null_share"]
        cells = []
        worst = 0.0
        for y in YEARS:
            a = pre[iso]["operable"][y]["null_share"]
            b = post[iso]["operable"][y]["null_share"]
            worst = max(worst, b or 0.0)
            cells.append(f"{_pct(a)} → **{_pct(b)}**")
        ok = "✔" if worst <= bar + 1e-12 else "✘"
        out.append(
            f"| {iso} | {_pct(bar)} | "
            + " | ".join(cells)
            + f" | {_pct(worst)} | {ok} |"
        )
    out += [
        "",
        "## §3a — the audit's heuristic (`bins`), post-F1 backcast default",
        "",
        "| ISO | bar (pre v2023 bins) | " + " | ".join(YEARS) + " | pass |",
        "|---|---|" + "---|" * len(YEARS) + "---|",
    ]
    for iso in ISOS:
        bar = pre_audit[iso]["operable"]["vintage_2023"]["bins_share"]
        vals = [post[iso]["operable"][y]["bins_share"] for y in YEARS]
        ok = "✔" if max(vals) <= bar + 1e-12 else "✘ (see note)"
        out.append(
            f"| {iso} | {_pct(bar)} | "
            + " | ".join(_pct(v) for v in vals)
            + f" | {ok} |"
        )
    out += [
        "",
        "The heuristic over-counts: the simple-cycle floor clamp (SPP-49) sets a "
        "sub-floor eGRID CT rate to `HEAT_RATE_BINS['gas_ct']['aero']`, and a "
        "measured or eGRID rate can coincide with a bin value. Where the two "
        "measures disagree, the `null` table above is the exact one.",
        "",
        "Layer check — eGRID alone (every measured flag OFF), post-F1:",
        "",
        "| ISO | " + " | ".join(YEARS) + " |",
        "|---|" + "---|" * len(YEARS),
    ]
    for iso in ISOS:
        out.append(
            f"| {iso} | "
            + " | ".join(_pct(post_eg[iso]["operable"][y]["null_share"]) for y in YEARS)
            + " |"
        )
    out += [
        "",
        "## §3b — within-window retirees at a class-table rate (MW null / MW online)",
        "",
        "| ISO | " + " | ".join(YEARS[:-1]) + " |",
        "|---|" + "---|" * (len(YEARS) - 1),
    ]
    for iso in ISOS:
        cells = []
        for y in YEARS[:-1]:
            a = pre[iso]["retirees"][y]
            b = post[iso]["retirees"][y]
            cells.append(
                f"{a['null_mw']:,.0f}/{a['thermal_mw']:,.0f} → "
                f"**{b['null_mw']:,.0f}/{b['thermal_mw']:,.0f}**"
            )
        out.append(f"| {iso} | " + " | ".join(cells) + " |")
    out += [
        "",
        "## Residual class-table MW per ISO-year (post-F1 backcast default, exact measure)",
        "",
        "| ISO | " + " | ".join(YEARS) + " |",
        "|---|" + "---|" * len(YEARS),
    ]
    for iso in ISOS:
        out.append(
            f"| {iso} | "
            + " | ".join(f"{post[iso]['operable'][y]['null_mw']:,.1f}" for y in YEARS)
            + " |"
        )
    out += [
        "",
        "## Residual class-table plants (no in-window eGRID rate in ANY vintage 2018-2024)",
        "",
        "Operable fleet, post-F1 backcast default, per ISO: the union over "
        "2019-2025 of plants whose source row has no eGRID rate, with the years "
        "each appears and its largest class-table MW in any year.",
        "",
    ]
    for iso in ISOS:
        plants: dict[int, dict] = {}
        for y in YEARS:
            for r in post[iso]["operable"][y]["residual"]:
                p = plants.setdefault(
                    r["plant_code"],
                    {"name": r["name"], "fuels": set(), "years": [], "mw": 0.0},
                )
                p["fuels"] |= set(r["fuels"])
                p["years"].append(y)
                p["mw"] = max(p["mw"], r["mw"])
        out.append(f"### {iso} — {len(plants)} plants")
        out.append("")
        if not plants:
            out.append("_none_")
            out.append("")
            continue
        out.append("| plant | name | fuels | max MW | years |")
        out.append("|---|---|---|---|---|")
        for code, p in sorted(plants.items(), key=lambda kv: -kv[1]["mw"]):
            ys = p["years"]
            span = f"{ys[0]}–{ys[-1]}" if len(ys) > 1 else ys[0]
            out.append(
                f"| {code} | {p['name']} | {', '.join(sorted(p['fuels']))} | "
                f"{p['mw']:,.1f} | {span} |"
            )
        out.append("")
    out += ["## Residual within-window retirees at a class-table rate", ""]
    for iso in ISOS:
        plants = {}
        for y in YEARS[:-1]:
            for r in post[iso]["retirees"][y]["residual"]:
                p = plants.setdefault(
                    r["plant_code"], {"name": r["name"], "fuels": set(), "mw": 0.0}
                )
                p["fuels"] |= set(r["fuels"])
                p["mw"] = max(p["mw"], r["mw"])
        if not plants:
            continue
        out.append(
            f"- **{iso}**: "
            + "; ".join(
                f"{c} {p['name']} ({', '.join(sorted(p['fuels']))}, {p['mw']:,.1f} MW)"
                for c, p in sorted(plants.items(), key=lambda kv: -kv[1]["mw"])
            )
        )
    (HERE / "census_summary.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
