#!/usr/bin/env python3
"""Idempotently insert the NEISO 2022 data-readiness record into out-of-sample.

Adds section 1.3 to ``docs/out-of-sample-results-2026-07.md`` via a unique ASCII
anchor, so the edit is byte-exact on the canonical doc without a whole-file
rewrite of the (em-dash-heavy) document. Run once by the marker-guarded
holdout-intake-neiso-2022.yml lander; safe to re-run (no-ops if already applied).
Docs only - not a solve.
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOC = REPO / "docs" / "out-of-sample-results-2026-07.md"

# Unique ASCII anchor at the end of section 1.2 (before the section-1 rule).
ANCHOR = "not holdout leakage.\n\n---"
MARKER = "### 1.3 Intake 2026-07-12"

SECTION = """### 1.3 Intake 2026-07-12 - NEISO 2022 validation-holdout data readiness

Executed under the owner's explicit, session-logged authorization of 2026-07-12
(`frontend/data/backcast/calibration-complete.json` intake_log): *"I (the owner)
explicitly authorize out-of-training data intake for NEISO 2022 in this session
under CLAUDE.md rule 22 (Option 2). ... Do NOT run any dispatch solve ... the
one-shot execution HOLD (G-19) stays in force; this session only gets the data
ready."* **No LP was constructed, solved, or scored**; the G-19 one-shot
execution HOLD stands. Every write is **MERGE-not-replace** with the 2023-2025
in-sample rows asserted **byte-frozen** first (no-LP validation: byte-identity /
loader-resolvability / row + date-range counts). The full series-by-series
equivalency audit is `docs/holdout-data-equivalency-register-2026-07.md`
(NEISO 2022: EQUIVALENT 21 / DEGRADED 2 / MISSING 1 non-default-limb /
accepted-absence 1).

Residual artifacts landed (retrieval date 2026-07-12; every one regenerates
deterministically from its committed producer via
`scripts/land_neiso_2022_readiness.py` and `fetch_algonquin_daily_spot.py`):

| Artifact | 2022 result | in-sample freeze |
|---|---|:--:|
| `neiso-weather/neiso_zone_temp_daily.csv` | +1,460 rows (4 zones x 365 d, committed 2022h1/h2 NOAA splits) | prefix byte-frozen |
| `neiso-weather/neiso_load_weighted_temp_daily.csv` | +365 rows (6-station derive_neiso re-fetch, frozen weighting) | prefix byte-frozen |
| `_validation-source/calibration_reference.json` + `NEISO_2022_renewable_capacity.csv` | splice `isos.NEISO.2022` (demand 116.98 TWh, 9 generation_twh fuels) + 120-row CSV | splice-proof (all else byte-identical) |
| `campd-unit-outages-NEISO.csv` | +502 2022-start windows (HEAD detector vintage - DEGRADED) | committed 968 byte-frozen |
| `_validation-source/actual_lmp.json` | splice NEISO 2022 **DA 85.56 / RT 84.92** (full field parity) | splice-proof |
| `frontend/data/backcast/tail/actual_tail.json` | splice NEISO 2022 **DA 27h / RT 117h** | splice-proof |
| `gas-prices/algonquin_citygate_daily.csv` | +62 daily prints (widened 2022 parser; 12/99 empty pages, was 42/99 - DEGRADED, weekly-anchored) | 123 committed rows byte-frozen |

Binaries land via the marker-guarded `.github/workflows/holdout-intake-neiso-2022.yml`
(the API file tools cannot carry binary content, and the large script-generated
text/data files are regenerated byte-exact on the runner rather than
hand-authored): the `plant_emission_rates_v2.parquet` NEISO-2022 frozen-row
merge, the `actual_lmp_hourly_NEISO.parquet` 2022 block, and the
`2022_smd_hourly.xlsx -> lmp-data/NEISO/` relocation, with a sha256 + row/date
integrity report in the run log. CAMPD unit-level 2022 for CT/MA/ME/NH/RI/VT was
already landed (2026-07-10 intake, section 1.2); the workflow's fetch step is
idempotent.

**Facility-level CAMPD 2022 is intentionally NOT fetched or materialized:**
`campd._read_one` resolves the facility series from the committed unit-level
extracts (facility-first, unit-level fallback; the TX-2023 parity is bit-for-bit,
F6), verified here for NEISO (MA_2022 -> 567,168 unit rows). Summing unit-level
by hour is exactly what the loader already does, so a second data fetch is
unnecessary (register: EQUIVALENT-via-fallback).

**Two DEGRADED / MISSING items are calibration-owner decisions, flagged not
fixed** (register DEGRADED-2 / MISSING-1): the outage-window detector-vintage
mismatch (committed 968 vs a 965 HEAD re-derive that drops the Merrimack coal
windows - 2022 is HEAD vintage), and the absent NEISO-AS measured hourly
reserve-requirement raws (only a README on disk for all years; needed by the
non-keeper dynamic-RR limb, so it does not block the frozen-keeper one-shot).
"""


def main() -> None:
    text = DOC.read_text()
    if MARKER in text:
        print("out-of-sample section 1.3 already present - skipping")
        return
    if text.count(ANCHOR) != 1:
        raise SystemExit(
            f"anchor not unique ({text.count(ANCHOR)} matches) - refusing to edit"
        )
    text = text.replace(ANCHOR, "not holdout leakage.\n\n" + SECTION + "\n---", 1)
    DOC.write_text(text)
    print("inserted out-of-sample section 1.3 (NEISO 2022 data readiness)")


if __name__ == "__main__":
    main()
