"""R-CAISO-5: generate the calibration attestation for the CC outage-derate-basis arm (± E).

Same logic as ``scripts/gen_rcaiso4_attestation.py``, ``scripts/gen_rcaiso3_attestation.py`` and ``scripts/gen_rcaiso_attestation.py`` (carried governance and DOF
ledger, C3c re-measured on the bundle); only the attestation text differs.

Original R-CAISO docstring follows.

R-CAISO: generate the calibration attestation for the corrected-inputs re-solve.

ZERO LP. Adapted from ``scripts/gen_xiso8_attestation.py`` (same ISO, same
carry-forward logic). This bundle is the incumbent keeper's recipe re-solved on
the F1/F2 corrected backcast inputs plus six ``--set`` arms of EXISTING
``ScenarioConfig`` fields (docs/handoffs/r-caiso/PRECOMMIT-r-caiso-2026-09-24.md
§1). No new field, no new threshold, no offer-curve change.

Carried forward from the source (outgoing keeper) bundle:

* ``governance`` booleans -- every arm is a measured input (EIA-860 vintage,
  eGRID / CEMS heat rates, CEMS outage windows); nothing is fitted to a residual
  or pinned to an actual. The arm posture was CHECKED leg-by-leg by
  ``scripts/probes/rcaiso_compose_span.py``.
* ``free_parameters`` (DOF ledger) -- unchanged, and VERIFIED unchanged below
  when the bundle already carries one. Measured inputs are identified by their
  source, not by a residual; the arms add no free parameter.

Re-measured: ``exceptions`` (C3c) from this bundle's own scorer output.
Written here: ``attested_by`` / ``note``.

Usage::

    python3 scripts/gen_rcaiso_attestation.py \\
        --bundle results/calibration/rcaiso_inputs_span \\
        --source results/calibration/xiso8_leftedge_span
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

ATTESTED_BY = """\
R-CAISO-5 (2026-09-26): the keeper 2026-09-26-caiso-r4-intertie-dam recipe re-solved one \
year per shard (rule 36) and composed at zero LP. ARMS (docs/handoffs/r-caiso-5/\
PRECOMMIT-r-caiso-5-2026-09-26.md): (X) unit_outage_extract_basis_share REPLACING \
unit_outage_lp_capacity_basis (mutually exclusive, rule 19) -- a CC outage window's removed \
share is taken on the CEMS extract's own capacity basis, so all units out means the plant \
is out (Moss Landing 2025: 207 MW phantom capacity -> 0 in its all-units-out windows; \
rule 14); optionally (E) cc_eia923_identity_emission_basis (R-CAISO-4). Both are measured \
inputs or construction repairs; ZERO new free parameters, no threshold, OFFER-CURVE \
MULTIPLIERS UNCHANGED, no authorized_price_tuning block. G-DRIFT 9a1980bc..c87cdc04: fleet \
arrays byte-identical in all four years; post-fleet hunks INERT for CAISO (PRECOMMIT \
section 3)."""

NOTE = """\
Attestation generated by scripts/gen_rcaiso5_attestation.py for an R-CAISO-5 composed \
bundle. Governance booleans and the DOF ledger are carried from the R-CAISO-4 keeper \
(rcaiso4_D_span); the C3c exceptions are re-measured on this bundle. Record: \
docs/handoffs/r-caiso-5/."""


def main(bundle: Path, source: Path, allow_empty: bool, scope_note: str) -> None:
    src = json.loads((source / "calibration_attestation.json").read_text())

    out = subprocess.run(
        [sys.executable, "scripts/calibration_verdict.py", str(bundle), "--json"],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    if out.returncode not in (0, 1):
        raise SystemExit(f"verdict failed rc={out.returncode}: {out.stderr[-500:]}")
    verdict = json.loads(out.stdout)

    # C3c exceptions, RE-MEASURED from this bundle rather than copied.
    exceptions = []
    for rec in verdict["criteria"]["price_tail"]["records"]:
        if rec.get("key") is not None or rec.get("status") != "FAIL":
            continue  # the DA diagnostic row is never gated
        exceptions.append(
            {
                "criterion": "price_tail",
                "year": rec["year"],
                "magnitude": (
                    f"model {rec['model']:.0f} h vs actual RT {rec['actual']:.0f} h "
                    "> $200/MWh (RE-MEASURED on this bundle's own committed sidecars)"
                ),
                "rationale": (
                    "C3c scarcity-tail model-class limitation (the ledgered "
                    "criterion; rubric v3.3 standing rule, v3.6 on a held-out "
                    "year) — adjudication belongs to the scorer"
                ),
            }
        )
    if not exceptions and not allow_empty:
        raise SystemExit(
            "no C3c FAIL found on this bundle — the ledger would be empty. "
            "That is a change from the outgoing keeper and must be looked at, "
            "not papered over. Pass --allow-empty-exceptions only when the "
            "bundle legitimately carries no ledgered caveat."
        )

    # RULE 21 [R-DOF]: the docstring claims the ledger is UNCHANGED because the
    # arm adds no free parameter. VERIFY it rather than assume it -- a boolean
    # construction gate should never become an entry, and if one ever did, this
    # stops the attestation instead of understating the ledger.
    own_path = bundle / "calibration_attestation.json"
    if own_path.exists():
        own = json.loads(own_path.read_text()).get("free_parameters")
        if own:

            def _names(fp):
                return {e.get("name") or e.get("parameter") for e in fp["entries"]}

            if (
                _names(own) != _names(src["free_parameters"])
                or own["n_entries"] != src["free_parameters"]["n_entries"]
                or own["n_residual"] != src["free_parameters"]["n_residual"]
            ):
                raise SystemExit(
                    "DOF ledger DIFFERS between this bundle and the source "
                    f"(arm {own['n_entries']}/{own['n_residual']} vs source "
                    f"{src['free_parameters']['n_entries']}/"
                    f"{src['free_parameters']['n_residual']}; added "
                    f"{sorted(_names(own) - _names(src['free_parameters']))}, "
                    f"removed {sorted(_names(src['free_parameters']) - _names(own))}). "
                    "The arm's 'zero free parameters' claim is FALSE -- fix the "
                    "attestation, do not carry the source's ledger."
                )
            print(
                f"  DOF ledger VERIFIED identical to source: "
                f"{own['n_entries']} entries / {own['n_residual']} residual"
            )

    att = {
        "schema": src["schema"],
        "governance": {
            **{
                k: v
                for k, v in src["governance"].items()
                if k not in ("attested_by", "note")
            },
            "attested_by": ATTESTED_BY + ("\n\n" + scope_note if scope_note else ""),
            "note": NOTE,
        },
        "exceptions": exceptions,
        "free_parameters": src["free_parameters"],
    }
    dst = bundle / "calibration_attestation.json"
    dst.write_text(json.dumps(att, indent=1, sort_keys=False))
    print(f"wrote {dst}")
    print(
        f"  governance flags carried : {sorted(k for k in att['governance'] if isinstance(att['governance'][k], bool))}"
    )
    print(
        f"  exceptions re-measured   : {[(e['year'], e['magnitude'][:34]) for e in exceptions]}"
    )
    print(
        f"  DOF ledger               : {att['free_parameters']['n_entries']} entries / {att['free_parameters']['n_residual']} residual (carried, unchanged)"
    )


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bundle", type=Path, required=True)
    ap.add_argument("--source", type=Path, required=True)
    ap.add_argument("--allow-empty-exceptions", action="store_true")
    ap.add_argument("--scope-note", default="")
    a = ap.parse_args()
    main(
        REPO / a.bundle if not a.bundle.is_absolute() else a.bundle,
        REPO / a.source if not a.source.is_absolute() else a.source,
        a.allow_empty_exceptions,
        a.scope_note,
    )
