"""R-CAISO-14: generate the calibration attestation for the EIA-930 clock-repair re-solve.

Same logic as ``scripts/gen_rcaiso11_attestation.py`` (carried governance and DOF
ledger, verified unchanged; C3c exceptions re-measured on the bundle); only the
attestation text differs. Used for both R-CAISO-14 composites: the 2022-2025 span
(source: the keeper ``rcaiso11_A_span``) and the 2019-2021 fold
(source: ``rcaiso11_A_tp_2019_2021``).

Usage::

    python3 scripts/gen_rcaiso14_attestation.py \\
        --bundle results/calibration/rcaiso13_A_span \\
        --source results/calibration/rcaiso11_A_span
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

ATTESTED_BY = """\
R-CAISO-14 (2026-09-29): the keeper 2026-09-28-caiso-r11-tacpst recipe re-solved one \
year per shard (rule 36) and composed at zero LP, with ONE delta \
(docs/handoffs/r-caiso-13/PRECOMMIT-r-caiso-13-2026-09-28.md section 2): \
caiso_eia930_clock_repair false -> true, the owner decision card 2026-09-28 "Build + \
solve now". A rule-14 SOURCE-CLOCK correction: the EIA-930 CISO extract's one-hour-late \
windows are re-stamped at the frame seam and in the caiso-80 supply-consistent demand. \
No floor added, no mechanism added. G-DRIFT 14c1d70e -> 332c8048: every non-arm hunk \
INERT (docs/handoffs/r-caiso-14/ADDENDUM-r-caiso-14-gdrift-2026-09-29.md). ZERO new \
free parameters, OFFER-CURVE BAND MULTIPLIERS UNCHANGED, no authorized_price_tuning block."""

NOTE = """\
Attestation generated by scripts/gen_rcaiso14_attestation.py for an R-CAISO-14 composed \
bundle. Governance booleans and the DOF ledger are carried from the --source bundle and \
verified; the C3c exceptions are re-measured on this bundle. Record: \
docs/handoffs/r-caiso-14/."""


def main(bundle: Path, source: Path, allow_empty: bool, scope_note: str) -> None:
    src = json.loads((source / "calibration_attestation.json").read_text())

    out = subprocess.run(
        [sys.executable, "scripts/calibration_verdict.py", str(bundle), "--json"],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    if out.returncode not in (0, 1):
        raise SystemExit(f"verdict failed rc={out.returncode}: {out.stderr[-500:]}")
    verdict = json.loads(out.stdout)

    # C3c exceptions, RE-MEASURED from this bundle rather than copied.
    exceptions = []
    for rec in verdict["criteria"]["price_tail"]["records"]:
        if rec.get("key") is not None or rec.get("status") != "FAIL":
            continue  # the DA diagnostic row is never gated
        exceptions.append(
            {
                "criterion": "price_tail",
                "year": rec["year"],
                "magnitude": (
                    f"model {rec['model']:.0f} h vs actual RT {rec['actual']:.0f} h "
                    "> $200/MWh (RE-MEASURED on this bundle's own committed sidecars)"
                ),
                "rationale": (
                    "C3c scarcity-tail model-class limitation (the ledgered "
                    "criterion; rubric v3.3 standing rule, v3.6 on a held-out "
                    "year) — adjudication belongs to the scorer"
                ),
            }
        )
    if not exceptions and not allow_empty:
        raise SystemExit(
            "no C3c FAIL found on this bundle — the ledger would be empty. "
            "That is a change from the outgoing keeper and must be looked at, "
            "not papered over. Pass --allow-empty-exceptions only when the "
            "bundle legitimately carries no ledgered caveat."
        )

    # RULE 21 [R-DOF]: the docstring claims the ledger is UNCHANGED because the
    # arm adds no free parameter. VERIFY it rather than assume it -- a boolean
    # construction gate should never become an entry, and if one ever did, this
    # stops the attestation instead of understating the ledger.
    own_path = bundle / "calibration_attestation.json"
    if own_path.exists():
        own = json.loads(own_path.read_text()).get("free_parameters")
        if own:

            def _names(fp):
                return {e.get("name") or e.get("parameter") for e in fp["entries"]}

            if (
                _names(own) != _names(src["free_parameters"])
                or own["n_entries"] != src["free_parameters"]["n_entries"]
                or own["n_residual"] != src["free_parameters"]["n_residual"]
            ):
                raise SystemExit(
                    "DOF ledger DIFFERS between this bundle and the source "
                    f"(arm {own['n_entries']}/{own['n_residual']} vs source "
                    f"{src['free_parameters']['n_entries']}/"
                    f"{src['free_parameters']['n_residual']}; added "
                    f"{sorted(_names(own) - _names(src['free_parameters']))}, "
                    f"removed {sorted(_names(src['free_parameters']) - _names(own))}). "
                    "The arm's 'zero free parameters' claim is FALSE -- fix the "
                    "attestation, do not carry the source's ledger."
                )
            print(
                f"  DOF ledger VERIFIED identical to source: "
                f"{own['n_entries']} entries / {own['n_residual']} residual"
            )

    att = {
        "schema": src["schema"],
        "governance": {
            **{
                k: v
                for k, v in src["governance"].items()
                if k not in ("attested_by", "note")
            },
            "attested_by": ATTESTED_BY + ("\n\n" + scope_note if scope_note else ""),
            "note": NOTE,
        },
        "exceptions": exceptions,
        "free_parameters": src["free_parameters"],
    }
    dst = bundle / "calibration_attestation.json"
    dst.write_text(json.dumps(att, indent=1, sort_keys=False))
    print(f"wrote {dst}")
    print(
        f"  governance flags carried : {sorted(k for k in att['governance'] if isinstance(att['governance'][k], bool))}"
    )
    print(
        f"  exceptions re-measured   : {[(e['year'], e['magnitude'][:34]) for e in exceptions]}"
    )
    print(
        f"  DOF ledger               : {att['free_parameters']['n_entries']} entries / {att['free_parameters']['n_residual']} residual (carried, unchanged)"
    )


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bundle", type=Path, required=True)
    ap.add_argument("--source", type=Path, required=True)
    ap.add_argument("--allow-empty-exceptions", action="store_true")
    ap.add_argument("--scope-note", default="")
    a = ap.parse_args()
    main(
        REPO / a.bundle if not a.bundle.is_absolute() else a.bundle,
        REPO / a.source if not a.source.is_absolute() else a.source,
        a.allow_empty_exceptions,
        a.scope_note,
    )
