"""Reserve co-optimization model package (layering fix, session 3E).

Created 2026-07-21 (refactor-consolidation plan §5 item 5): the unified
reserve co-optimization configuration — per-ISO ``ReserveDesign`` builders,
reserve-product constants, and the dispatch-kwargs bridge consumed by
``dispatch._build_reserve_rows`` — is model-layer physics, and importing it
from ``config/`` inverted the config→data→model layering. The 2,932-line
module moved INTACT to :mod:`.spec` (rule 25: the per-ISO ``_<iso>_design``
registries transplant byte-for-byte); later sessions may split ``spec``
further.

Compatibility contract: ``market_sim.config.reserve_config`` (the historical
import path used by src, scripts, and the tests) is a facade that aliases
itself to :mod:`.spec` via ``sys.modules``, so the historical path and the
spec module are ONE namespace object. This ``__init__`` additionally
re-exports the full spec surface so the layered
``from market_sim.model.reserves import <name>`` path works for every name.
The surface is pinned by ``tests/test_config_model_layering.py``.
"""

from __future__ import annotations

from market_sim.model.reserves.spec import (  # noqa: F401
    CAISO_AS_SUSTAIN_DURATION_H,
    CAISO_CONTINGENCY_FRAC,
    CAISO_ENERGY_BID_CAP_SOFT,
    CAISO_HYDRO_RAMP10_FRAC,
    CAISO_NONSPIN_DEMAND_CURVE,
    CAISO_SPIN_DEMAND_CURVE,
    CAISO_SPIN_FRACTION,
    CALIBRATION_DIR,
    ERCOT_AS_ECRS_BASE_MW,
    ERCOT_AS_ECRS_MAX_MW,
    ERCOT_AS_ECRS_MIN_MW,
    ERCOT_AS_ECRS_RAMP_COEF,
    ERCOT_AS_ECRS_SIGMA_COEF,
    ERCOT_AS_FE_FRAC_LOAD,
    ERCOT_AS_FE_FRAC_SOLAR,
    ERCOT_AS_FE_FRAC_WIND,
    ERCOT_AS_NSPIN_BASE_MW,
    ERCOT_AS_NSPIN_LOAD_COEF,
    ERCOT_AS_NSPIN_MAX_MW,
    ERCOT_AS_NSPIN_MIN_MW,
    ERCOT_AS_NSPIN_RAMP_COEF,
    ERCOT_AS_PLAN_HOLD_EPS,
    ERCOT_AS_PRODUCTS,
    ERCOT_AS_PRODUCT_DURATION_H,
    ERCOT_AS_RAMP_WINDOW_HOURS,
    ERCOT_AS_REGUP_FLOOR_MW,
    ERCOT_AS_REGUP_MAX_MW,
    ERCOT_AS_REGUP_MIN_MW,
    ERCOT_AS_REGUP_SIGMA_COEF,
    ERCOT_AS_RRS_FLOOR_MW,
    ERCOT_AS_RRS_INERTIA_COEF_MW,
    ERCOT_AS_RRS_MAX_MW,
    ERCOT_ECRS_RELEASE_REFORM_HOUR,
    ERCOT_ECRS_RELEASE_REFORM_YEAR,
    ERCOT_LR_RRS_ENROLL_BASE_MW,
    ERCOT_LR_RRS_ENROLL_BASE_YEAR,
    ERCOT_LR_RRS_ENROLL_CAP_MW,
    ERCOT_LR_RRS_ENROLL_GROWTH_MW_PER_YR,
    FUEL_TYPE_NAMES,
    FleetArrays,
    MISO_EMERGENCY_TIER1_OFFER_FLOOR,
    MISO_EMERGENCY_TIER2_OFFER_FLOOR,
    MISO_MIDWEST_ZONES,
    MISO_REGULATING_RESERVE_MW,
    MISO_RESERVE_DEMAND_CURVE_CRITICAL_MW,
    MISO_RESERVE_DEMAND_CURVE_MAX,
    MISO_RPE_DEMAND_VALUE,
    MISO_ZONAL_ORDC_STEPS,
    MISO_ZONAL_RESERVE_DEFAULT_ZONES,
    NEISO_RCPF_PRODUCTS,
    NYISO_DOWNSTATE_SPIN_ZONES,
    NYISO_RCPF_LOCATIONAL,
    NYISO_RCPF_PRODUCTS,
    NYISO_SPIN_FRACTION,
    ORDC_FLOOR_START_HOUR_2023,
    ORDC_FLOOR_STEPS,
    PJM_MAD_ZONES,
    PJM_ORDC_CURVE_PATH,
    PJM_PERGEN_SIZE_SPLIT_MEAN_MULTIPLE,
    PJM_PRIMARY_RESERVE_LSC_FACTOR,
    POSTURE_FAST_START_MIN_DOWN_H,
    POSTURE_FAST_START_STARTUP_PER_MW,
    QUICK_START_FUEL_TYPES,
    RESERVE_FUEL_TYPES,
    ReserveDesign,
    ReserveFamily,
    build_reserve_dispatch_kwargs,
    caiso_pergen_pool_ramp10,
    caiso_pergen_structure,
    ercot_commitment_headroom_overrides,
    ercot_commitment_posture_spec,
    get_reserve_design,
    pjm_pergen_pool_ramp10,
    pjm_pergen_structure,
    _ERCOT_POSTURE_CHP_GROUPS as _ERCOT_POSTURE_CHP_GROUPS,
    _caiso_design as _caiso_design,
    _caiso_locational_as_families as _caiso_locational_as_families,
    _caiso_reserve_eligible as _caiso_reserve_eligible,
    _ercot_design as _ercot_design,
    _ercot_multiproduct_design as _ercot_multiproduct_design,
    _miso_design as _miso_design,
    _neiso_design as _neiso_design,
    _nyiso_design as _nyiso_design,
    _pjm_design as _pjm_design,
    _posture_pool_params as _posture_pool_params,
    _quick_start_eligible as _quick_start_eligible,
    _reserve_eligible as _reserve_eligible,
)

__all__ = [
    "CAISO_AS_SUSTAIN_DURATION_H",
    "CAISO_CONTINGENCY_FRAC",
    "CAISO_ENERGY_BID_CAP_SOFT",
    "CAISO_HYDRO_RAMP10_FRAC",
    "CAISO_NONSPIN_DEMAND_CURVE",
    "CAISO_SPIN_DEMAND_CURVE",
    "CAISO_SPIN_FRACTION",
    "CALIBRATION_DIR",
    "ERCOT_AS_ECRS_BASE_MW",
    "ERCOT_AS_ECRS_MAX_MW",
    "ERCOT_AS_ECRS_MIN_MW",
    "ERCOT_AS_ECRS_RAMP_COEF",
    "ERCOT_AS_ECRS_SIGMA_COEF",
    "ERCOT_AS_FE_FRAC_LOAD",
    "ERCOT_AS_FE_FRAC_SOLAR",
    "ERCOT_AS_FE_FRAC_WIND",
    "ERCOT_AS_NSPIN_BASE_MW",
    "ERCOT_AS_NSPIN_LOAD_COEF",
    "ERCOT_AS_NSPIN_MAX_MW",
    "ERCOT_AS_NSPIN_MIN_MW",
    "ERCOT_AS_NSPIN_RAMP_COEF",
    "ERCOT_AS_PLAN_HOLD_EPS",
    "ERCOT_AS_PRODUCTS",
    "ERCOT_AS_PRODUCT_DURATION_H",
    "ERCOT_AS_RAMP_WINDOW_HOURS",
    "ERCOT_AS_REGUP_FLOOR_MW",
    "ERCOT_AS_REGUP_MAX_MW",
    "ERCOT_AS_REGUP_MIN_MW",
    "ERCOT_AS_REGUP_SIGMA_COEF",
    "ERCOT_AS_RRS_FLOOR_MW",
    "ERCOT_AS_RRS_INERTIA_COEF_MW",
    "ERCOT_AS_RRS_MAX_MW",
    "ERCOT_ECRS_RELEASE_REFORM_HOUR",
    "ERCOT_ECRS_RELEASE_REFORM_YEAR",
    "ERCOT_LR_RRS_ENROLL_BASE_MW",
    "ERCOT_LR_RRS_ENROLL_BASE_YEAR",
    "ERCOT_LR_RRS_ENROLL_CAP_MW",
    "ERCOT_LR_RRS_ENROLL_GROWTH_MW_PER_YR",
    "FUEL_TYPE_NAMES",
    "FleetArrays",
    "MISO_EMERGENCY_TIER1_OFFER_FLOOR",
    "MISO_EMERGENCY_TIER2_OFFER_FLOOR",
    "MISO_MIDWEST_ZONES",
    "MISO_REGULATING_RESERVE_MW",
    "MISO_RESERVE_DEMAND_CURVE_CRITICAL_MW",
    "MISO_RESERVE_DEMAND_CURVE_MAX",
    "MISO_RPE_DEMAND_VALUE",
    "MISO_ZONAL_ORDC_STEPS",
    "MISO_ZONAL_RESERVE_DEFAULT_ZONES",
    "NEISO_RCPF_PRODUCTS",
    "NYISO_DOWNSTATE_SPIN_ZONES",
    "NYISO_RCPF_LOCATIONAL",
    "NYISO_RCPF_PRODUCTS",
    "NYISO_SPIN_FRACTION",
    "ORDC_FLOOR_START_HOUR_2023",
    "ORDC_FLOOR_STEPS",
    "PJM_MAD_ZONES",
    "PJM_ORDC_CURVE_PATH",
    "PJM_PERGEN_SIZE_SPLIT_MEAN_MULTIPLE",
    "PJM_PRIMARY_RESERVE_LSC_FACTOR",
    "POSTURE_FAST_START_MIN_DOWN_H",
    "POSTURE_FAST_START_STARTUP_PER_MW",
    "QUICK_START_FUEL_TYPES",
    "RESERVE_FUEL_TYPES",
    "ReserveDesign",
    "ReserveFamily",
    "build_reserve_dispatch_kwargs",
    "caiso_pergen_pool_ramp10",
    "caiso_pergen_structure",
    "ercot_commitment_headroom_overrides",
    "ercot_commitment_posture_spec",
    "get_reserve_design",
    "pjm_pergen_pool_ramp10",
    "pjm_pergen_structure",
]
